Function-based storage control strategy
idaholab/HERON pull request #103
Opened 2021-08-30 17:31 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Addresses #102 (not completely resolved).

##### What are the significant changes in functionality due to this change request?
Adds the ability to define a `<strategy>` for `<stores>` Components and provide a Function to govern the dispatch decision making (regardless of the optimization). Note this function will likely require advanced HERON understanding of the variables in place to use effectively.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-08-30 17:32 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +from numpy.lib.recfunctions import assign_fields_by_name
I think VSCode added this for me when I didn't need it. I'll remove it as part of addressing review comments.

2021-09-16 20:59 UTC, PaulTalbot-INL commented
@dylanjm Binghui and I looked through this, and I think it's ready for review.

2021-09-16 22:21 UTC, dylanjm requested changes
Everything looks good. A few minor changes.

2021-09-16 22:21 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +from numpy.lib.recfunctions import assign_fields_by_name
Did you still want to remove this?

2021-09-16 22:21 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      if intr.is_governed(): #intr.is_type('Storage') and intr.get_strategy() is not None:
Looks like there is some left-over logic here. Please remove if not needed.

2021-09-16 22:21 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      #if intr.is_type('Storage') and intr.get_strategy() is not None:
Might be worthwhile to remove this logic but keep the TODO comment.

2021-09-16 22:47 UTC, dylanjm approved these changes
Looks good. I'll go ahead and merge

2021-09-16 22:49 UTC, merged