Round-Trip Efficiency
idaholab/HERON pull request #109
Opened 2021-11-02 20:43 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #108

##### What are the significant changes in functionality due to this change request?
Implements RTE, with "half" (sqrt) of the efficiency applied on charging and the other portion on discharging.

Also splits storage-related dispatch variables from single tracker:
- "production", reporting the level

to three trackers:
- "level", reporting the level
- "charge", reporting charge activities,
- "discharge", reporting discharge activities

This required some renaming of dispatch variables to `Dispatch__{comp}__{tracker}__{resource}`.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-11-03 23:29 UTC, dylanjm requested changes
Looks mostly good, just a few comments on docstrings and file organization.

2021-11-03 23:29 UTC, dylanjm commented on src/Components.py
> +    self._sqrt_rte = 1.0                # sqrt of the round-trip efficiency for this interaction
I might be missing something, wouldn't we want to avoid setting a default value for this variable? Shouldn't it be dynamic for each component?

2021-11-03 23:29 UTC, dylanjm commented on src/Components.py
> +    self._sqrt_rte = 1.0                # sqrt of the round-trip efficiency for this interaction
I realize later that we are assuming a default value of 100% for RTE. So this is a non-issue.

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/DispatchState.py
> +  def set_activity_indexed(self, *args, **kwargs):
Does the doctrings need to be changed now that we are accepting `*args`?

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +    if True: #self.debug_mode:
This can probably be cleaned up if we are going to keep it this way.

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, values, array(float), values to set for param
Is there an actual `array` data structure native to python? I think it would it would be more clear if it was specified as `list` or `np.array`

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, kwargs, dict, optional, passalong kwargs to pyomo variable
space here in `passalong`

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      tag = 'production'
I can't remember, would it be bad practice to specify 'production' as the default value in the function parameters?

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +    #     prod[limit_r, t].fix(caps[t])
Do we need to leave the commented code in?

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, t, int, time index for capacity rule
Specify an `@Out` parameter in this doc string.

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, t, int, time index for capacity rule
Specify an `@Out` parameter for this doc string.

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, t, int, time index for capacity rule
Specify an `@Out` parameter for this doc string.

2021-11-03 23:29 UTC, dylanjm commented on src/dispatch/twin_pyomo_test_rte.py
> +# Copyright 2020, Battelle Energy Alliance, LLC
Is there a particular reason we can't make these integration tests?

2021-11-03 23:30 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +    if True: #self.debug_mode:
What I mean by this is removing the unnecessary conditional.

2021-11-08 14:45 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +      @ In, kwargs, dict, optional, passalong kwargs to pyomo variable
I think passalong is a valid albeit casual adjective, right?

2021-11-08 14:47 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +      tag = 'production'
I debate this frequently, and have unofficially tried to set these at the top of the method so as not to list the default. However, I know there are some UIs that will show the docstrings as a preview, and that wouldn't show the default. I'll change this one.

2021-11-08 14:48 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +    #     prod[limit_r, t].fix(caps[t])
I'll add a comment about why this is left in; I suspect we'll need something like it for some solvers.

2021-11-08 14:52 UTC, PaulTalbot-INL commented on src/dispatch/twin_pyomo_test_rte.py
> +# Copyright 2020, Battelle Energy Alliance, LLC
This is a good idea; I've been using them as a developer sandbox for figuring out pyomo. Maybe for now we merge it, then we talk about how we want to use and maintain these scripts for a mini rework.

2021-11-08 15:31 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      @ In, kwargs, dict, optional, passalong kwargs to pyomo variable
Just looked it up, I didn't realize it was spelled that way. Sounds good to me.

2021-11-08 15:32 UTC, dylanjm commented on src/dispatch/twin_pyomo_test_rte.py
> +# Copyright 2020, Battelle Energy Alliance, LLC
Sounds good to me.

2021-11-08 16:16 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +      tag = 'production'
I know there are a few other methods that do this same thing, I think consistency across the methods would be more important. So I'll leave it up to you whether you want to change them all or not.

2021-11-08 16:17 UTC, dylanjm reviewed
Everything looking good, just a few more minor updates.

2021-11-08 18:11 UTC, dylanjm approved these changes
Looks like I was looking at the wrong commit updates. Everything is resolved.

2021-11-08 18:12 UTC, merged