Optimizer settings in HERON input
idaholab/HERON pull request #137
Opened 2022-02-21 14:19 UTC by dgarrett622

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #132 

##### What are the significant changes in functionality due to this change request?

- EconomicRatio PostProcessor now used (BasicStatistics metrics available through EconomicRatio)
- User can specify statistical metric used as objective for optimization in the HERON input file
- User can specify min or max for optimization in the HERON input file
- Uploaded integration test for new functionality
- Updated Tester so that HERON integration tests can be run locally on Windows

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-02-21 14:30 UTC, PaulTalbot-INL requested changes
A couple minor comments to consider

2022-02-21 14:30 UTC, PaulTalbot-INL commented on src/Cases.py
> +                            \default{max}"""
How painful would it be to have the default based on the metric? I suspect we want default for VaR to be minimize, for example.

2022-02-21 14:30 UTC, PaulTalbot-INL commented on src/Testers/HeronIntegrationTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, 'main.py')
We should talk about this change; does the "heron" executable not work on Windows at all?

The "executable" lets us handle things like loading the conda env, so I'm not thrilled by bypassing it entirely in the testing system.

2022-02-21 14:30 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimization_settings/heron_input.xml
> +    -->
can we remove the un-useful commented blocks in this test? I know they need to be removed from some of the other tests as well.

2022-02-21 14:30 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimization_settings/write_inner.py
> +import xml.etree.ElementTree as ET
this file is generated by the heron template run, and so doesn't need to be included in the repo

2022-02-21 17:20 UTC, dgarrett622 commented on src/Cases.py
> +                            \default{max}"""
I could set up a default mapping that maps each metric to min or max. This should not be difficult to implement.

2022-02-21 17:22 UTC, dgarrett622 commented on tests/integration_tests/mechanics/optimization_settings/heron_input.xml
> +    -->
I can clean up the comments in this test. Should I remove the commented blocks in other tests for this PR?

2022-02-21 17:22 UTC, dgarrett622 commented on tests/integration_tests/mechanics/optimization_settings/write_inner.py
> +import xml.etree.ElementTree as ET
Oops, grabbed one too many files. I'll remove it.

2022-02-21 17:27 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimization_settings/heron_input.xml
> +    -->
I think just this one is fine, but if you want to clear out the others I would not object!

2022-02-21 17:29 UTC, dgarrett622 commented on src/Testers/HeronIntegrationTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, 'main.py')
Let's talk about this in our developer meeting.

2022-02-21 22:49 UTC, dgarrett622 commented on src/Testers/HeronIntegrationTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, 'main.py')
Looks like the original implementation does not work on my Windows setup. However, prepending "bash.exe" to the "heron" executable seems to do the trick. It looks like that's how RrR works as well. I'll implement a check for Windows OS and add "bash.exe" to keep the "heron" executable.

2022-02-21 23:03 UTC, PaulTalbot-INL commented on src/Testers/HeronIntegrationTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, 'main.py')
It's good to have a dev on windows! We'll find a lot more of these issues a priori.

2022-02-22 16:22 UTC, PaulTalbot-INL approved these changes

2022-02-22 16:22 UTC, merged