Workshop March 2022 Examples
idaholab/HERON pull request #139
Opened 2022-03-10 17:36 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-03-18 17:48 UTC, dgarrett622 requested changes
I pulled your branch locally and tried to run the test to make sure it runs on a Windows machine. It failed for two reasons: 

1. GLPK can only be run serially, there is no "threads" option. 
2. Specifying 10 for <parallel> is too many cores for my machine (max 8).

Commenting out the "threads" option and specifying 6 for <parallel> allowed the test to run successfully for my setup. I think the fixes for these two issues are pretty simple to implement and will ensure that the test runs on Windows.

2022-03-18 17:48 UTC, dgarrett622 commented on src/dispatch/pyomo_dispatch.py
> +      solve_options = {'threads': 2}
Setting "threads" does not work for GLPK. The options passed into "solve" appear to be specific to the solver used. I'm sure this is an option for CBC, but it throws an error when using GLPK. I don't know what the behavior is if other solvers are used.

2022-03-18 17:48 UTC, dgarrett622 commented on templates/template_driver.py
> +    if case.innerParallel:
See the previous comment on os.cpu_count()

2022-03-18 17:48 UTC, dgarrett622 commented on templates/template_driver.py
> +    print()
Empty print statement can be deleted.

2022-03-18 17:48 UTC, dgarrett622 commented on templates/template_driver.py
> +      run_info.find('batchSize').text = f'{case.innerParallel}'
See the previous comment on os.cpu_count().

2022-03-18 17:48 UTC, dgarrett622 commented on src/Cases.py
> +              number and \xmlNode{inner} should be at most the number of parallel process availabe on
"available"

2022-03-18 17:48 UTC, dgarrett622 commented on templates/template_driver.py
> +  #var_template.append(xmlUtils.newNode('grid', attrib={'type':'value', 'construction':'custom'}))
This appears to be commented out, does it need to stay or can it be deleted?

2022-03-18 17:48 UTC, dgarrett622 commented on src/Cases.py
> +            self.innerParallel = sub.value
I tried running the htse test case and an error was thrown because more cores were requested than available (my Windows machine has 8). I think it would be a good idea to check the number of available cores using "os.cpu_count()" and make sure that the user specified number is not greater than the maximum number available or some threshold. Generally, I try to only use max os.cpu_count() -1 cores so that it doesn't lock up my machine. Probably should add a debug or warning message if the user specifies too many cores and the number is adjusted downward to allow the case to run.

2022-03-18 17:53 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +      solve_options = {'threads': 2}
Interesting; I don't recall adding this line; I must have been experimenting with something I didn't finalize. I can remove this. Philosophically I think it should only be set based on user requests specific to individual solvers.

2022-03-18 17:55 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +      solve_options = {'threads': 2}
I think perhaps there are pieces of your top comment above that aren't showing. I think you have to escape XML nodes as `<example>` otherwise they get treated as formatting tags such as "<example>".

2022-03-18 17:59 UTC, dgarrett622 commented on src/dispatch/pyomo_dispatch.py
> +      solve_options = {'threads': 2}
Yeah, forgot the backticks on that one. Preview function is your friend.

2022-03-18 19:42 UTC, PaulTalbot-INL commented on src/Cases.py
> +            self.innerParallel = sub.value
That's a good thought. That check won't work well when we're running on HPC, but we can follow up with that in a future PR where we auto-handle HPC stuff.

2022-03-18 19:50 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +  #var_template.append(xmlUtils.newNode('grid', attrib={'type':'value', 'construction':'custom'}))
removed

2022-03-18 19:51 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +    if case.innerParallel:
hopefully the check I added will catch this, let me know if you think anything further should be done

2022-03-18 19:51 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +      run_info.find('batchSize').text = f'{case.innerParallel}'
same, let me know if you think anything more needs doing

2022-03-22 14:39 UTC, dgarrett622 requested changes
Looks like the automated tests are failing and I think I know why. A quick fix and a comment to consider.

2022-03-22 14:39 UTC, dgarrett622 commented on src/Cases.py
> +        self.raiseAWarning('System may be overloaded and greatly increase run time! ' +
Just a comment for consideration:

On my Windows machine, requesting more cores than you have available results in an error and RAVEN will not run, not sure what the behavior is on Mac or Linux. We could raise an error here or raise a warning and wait for RAVEN to throw an error later, either way is probably fine. I think the important thing is to inform the user that they requested more cores than the machine has available. If that particular error is thrown later, the user will have an idea as to why the simulations were not run.

2022-03-22 14:39 UTC, dgarrett622 commented on src/dispatch/pyomo_dispatch.py
>        soln = pyo.SolverFactory(self._solver).solve(m, options=solve_options)
I'm pretty sure this is what is causing the automated tests to fail. Removing the `options=solve_options` should fix this.

2022-03-22 16:26 UTC, PaulTalbot-INL commented on src/Cases.py
> +        self.raiseAWarning('System may be overloaded and greatly increase run time! ' +
Yeah, I don't love how this is handled generally speaking; I think handling it better in RAVEN may lead to sensible error messages so we don't duplicate that effort in HERON.

2022-03-22 16:26 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
>        soln = pyo.SolverFactory(self._solver).solve(m, options=solve_options)
whoops! fixed.

2022-03-22 18:10 UTC, dgarrett622 approved these changes

2022-03-22 18:13 UTC, merged