Loading data from HYBRID to HERON (economic information only)
idaholab/HERON pull request #143
Opened 2022-04-06 16:51 UTC by Botros-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Transferring data from HYBRID text file to HERON input XML file

##### What are the significant changes in functionality due to this change request?
Facilitate the HYBRID/HERON integration

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-04-13 20:47 UTC, Botros-INL commented
@PaulTalbot-INL 
Hi Paul, I think the pull request is ready now for the review. Thank you.

2022-04-13 21:10 UTC, PaulTalbot-INL commented
It looks like the precheck had concerns, copying the message here:
```
##########################################################################
ERROR: The following files contain trailing whitespace after applying your patch:
	tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py

Run the "delete_trailing_whitespace.sh" script in your $MOOSE_DIR/scripts directory.
##########################################################################
```

2022-04-13 21:34 UTC, PaulTalbot-INL requested changes
Here's a few starting comments to consider. This is coming along well!

I didn't notice any `tests` file getting modified; we need to add using this script and then running the resulting HERON file as a regression test. Let me know and we can talk about how all that works, if that would help.

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/heron_input.xml
> +<HERON>
was this file included by accident? If not, how is it related to the changes?

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +  """xml_node1 is applicable to the component lifetime and depreciate nodes"""
Take a look at the standards for function definitions at https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#function-and-class-documentation-strings. The standards for docsstrings are very (possibly unnecessarily) specific, and need to list each input and output for each function.

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +Hybrid_input_folder, HERON_input_file = sys.argv[1], sys.argv[2]
We should consider implementing an `argparse` approach to command line arguments for maintainability and to help users understand the script. That doesn't necessarily need to be part of this PR; perhaps create an issue to track it?

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +output_file = "new_" + (os.path.basename(HERON_input_file))
I'm not sold on `"new_"`, what about something like `"filled_"`?

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +    Hybrid_keywords.append(lines[0])
someday we should load these directly from HYBRID. This is fine for now.

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +"""
for comments within the body of a module, use `#` and reserve `"""` for docstrings. For more visibility, you can do something fancier, such as
```python
#####
# Section Name
# section description with more words
#
```

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +def prettify(tree):
I think we provide utils for this in RAVEN, maybe in the `utils` module? Can we use that rather than duplicate the code here?

2022-04-13 21:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +"""
docstring use in module; should probably be `#` instead

2022-04-30 03:35 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/heron_input.xml
> +<HERON>
Now, I have a pre_heron_input.xml file (before autoloading info from HYBRID) plus the heron_input.xml file (after loading info from HYBRID)

2022-04-30 03:35 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +  """xml_node1 is applicable to the component lifetime and depreciate nodes"""
Thank you. I did

2022-04-30 03:35 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +Hybrid_input_folder, HERON_input_file = sys.argv[1], sys.argv[2]
I did.

2022-04-30 03:35 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +output_file = "new_" + (os.path.basename(HERON_input_file))
Now, I have a pre_heron_input.xml file (before autoloading info from HYBRID) plus the heron_input.xml file (after loading info from HYBRID)

2022-04-30 03:36 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +"""
Done.

2022-04-30 03:36 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +def prettify(tree):
Yes, I did that.

2022-04-30 03:36 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_heron_integration/htse/hybrid2heron.py
> +"""
I modified it.

2022-05-02 14:42 UTC, PaulTalbot-INL commented
Based on the tests, it looks like there's a pathing issue to fix when trying to load from "scripts".

2022-05-02 14:46 UTC, PaulTalbot-INL commented
Theres's some extraneous files that slipped into the commit, such as `*.DS_Store`, `.ravenStatus`, `disp_results.nc`, `flex_meta.xml`, `heron.lib`, and other files down in "inner" runs such as `functions.py` (not the original, but copied versions). It looks like perhaps whole subfolders got copied and added as gold, maybe?

2022-05-02 16:51 UTC, PaulTalbot-INL reviewed
A couple comments, and then we have a call scheduled today to talk about python file structure to fix up the script.

2022-05-02 16:51 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_load/hybrid2heron_economic.py
> +    @ Out, all_hybrid_info, the relevant information from the HYBRID text files which includes: variables and their values and comments plus warning messages if necessary
missing type for all_hybrid_info

2022-05-02 16:51 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/hybrid_load/hybrid2heron_economic.py
> +    ...
What is the ellipses here meant to do? Do you mean to raise an error, or pass or ... ?

2022-05-03 20:07 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_load/hybrid2heron_economic.py
> +    @ Out, all_hybrid_info, the relevant information from the HYBRID text files which includes: variables and their values and comments plus warning messages if necessary
fixed it

2022-05-03 20:08 UTC, Botros-INL commented on tests/integration_tests/mechanics/hybrid_load/hybrid2heron_economic.py
> +    ...
fixed it. I modified it to (pass)

2022-05-03 20:09 UTC, Botros-INL commented
@PaulTalbot-INL 
Thank you so much, Paul. I edited the python script and I think that I fixed the pathing issue. Please let me know if more changes are needed.

2022-05-13 01:59 UTC, Botros-INL commented
@PaulTalbot-INL 
Hi Paul, I have added the user manual section (section #7) and opened a new issue motivating the development I did. I think the pull request is ready now for review. Thank you.

2022-05-13 17:19 UTC, PaulTalbot-INL commented
I don't think we upload the pdf itself, as it creates git history issues. Would you mind removing the PDF from the PR? You can keep it on your disk while removing it by using `git rm --cached HERON_user_manual.pdf`

2022-05-13 17:28 UTC, Botros-INL commented
@PaulTalbot-INL
I deleted the manual pdf just now.

2022-05-13 18:10 UTC, PaulTalbot-INL approved these changes

2022-05-13 18:11 UTC, merged