Changed HERON path variable in collect_tex.py
idaholab/HERON pull request #185
Opened 2022-07-19 18:30 UTC by AnthoneyGriffith

Changed heron_path in collect_tex.py so that the HERON module is found when compiling the documentation via make_docs.sh.
--------
Pull Request Description
--------
##### What issue does this change request address?
#184 

##### What are the significant changes in functionality due to this change request?
No changes in functionality.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-07-19 18:54 UTC, dylanjm approved these changes, later dismissed
Changes look good to me. No significant functionality changes, just need tests to pass and it can be merged. Thanks!

2022-07-19 18:54 UTC, dgarrett622 requested changes
A minor change and a comment.

2022-07-19 18:54 UTC, dgarrett622 commented on doc/user_manual/script/collect_tex.py
> +heron_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', '..'))
Inside of HERON/src/_utils.py there is a function `get_heron_loc()`. I would suggest using this function instead of hardcoding the location of the HERON path.

2022-07-19 18:54 UTC, dgarrett622 commented on doc/user_manual/script/collect_tex.py
>  # sys.path.append(framework_path)
I would remove unused imports to make this cleaner.

2022-07-19 19:01 UTC, AnthoneyGriffith commented on doc/user_manual/script/collect_tex.py
>  # sys.path.append(framework_path)
Are you referring to the commented lines under the primary import?

2022-07-19 19:03 UTC, dgarrett622 commented on doc/user_manual/script/collect_tex.py
>  # sys.path.append(framework_path)
Yes, I don't think there is a historical reason to keep the commented lines here.

2022-07-19 19:23 UTC, dgarrett622 commented
@dylanjm looks like we were reviewing this at the same time! Sorry, @AnthoneyGriffith I'm a bit more picky 😛

2022-07-19 21:13 UTC, AnthoneyGriffith commented on doc/user_manual/script/collect_tex.py
> +heron_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', '..'))
To have access to that method, I need to import HERON/src/_utils.py which feels circular to me. I am not sure how else I would do this import without writing out the heron_path as it is here. I may be missing something, if so please let me know.

2022-07-19 21:26 UTC, dgarrett622 commented on doc/user_manual/script/collect_tex.py
> +heron_path = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', '..'))
hm, this is why HERON should be installed as a Python package. Imports of HERON would work regardless of your working folder.

It looks like you can't do relative imports inside of the documentation folders. Either we include __init__.py in each folder to do relative imports of HERON or hard code the path. Simplest solution would be to use your hard coded fix, I vote for that.

2022-07-19 21:29 UTC, dgarrett622 approved these changes
Changes look good. Thanks for cleaning this up!

2022-07-20 14:18 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1115118/) on 89700d6 : invalidated by @dgarrett622

failed in updating RAVEN

2022-07-20 16:35 UTC, merged