Moped
idaholab/HERON pull request #187
Opened 2022-07-19 22:07 UTC by AnthoneyGriffith

--------
Pull Request Description
--------
##### What issue does this change request address?
#186 

##### What are the significant changes in functionality due to this change request?
Added `<case>` sub-node `<workflow>` that lets user select the workflow they wish to run for their analysis. Added MOPED workflow that builds and solves a single level optimization problem via pyomo and TEAL. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-07-19 22:53 UTC, dylanjm submitted a review, later dismissed
Made a first pass over. Got about half-way through `Moped.py`. Will do another review once some changes are made.

2022-07-19 22:53 UTC, dylanjm commented on src/Cases.py
> +        'inner_samples': 1,       # how many inner realizations to sample specifically for the debug run (not the same as self._num_samples)
I'm pretty sure that this value eventually gets set to `self._num_samples` so it's not entirely correct to say it's not the same.

2022-07-19 22:53 UTC, dylanjm commented on src/main.py
> +  elif sim._case._workflow == 'combined':
I'm still anti-combined. It doesn't make sense why the user would find it useful to run one workflow and then create a second one. My opinion is that it's complexity disguised as a feature. We prompt the user to make changes to the input file and rerun for other features. For example, running in debug mode. 

@PaulTalbot-INL thoughts on this?

2022-07-19 22:53 UTC, dylanjm commented on tests/workshop/simple/moped_input.xml
> +    <!-- <parallel>
remove commented stuff.

2022-07-19 22:53 UTC, dylanjm commented on tests/workshop/simple/moped_input.xml
> +    <author>talbpaul</author>
change author, probably give it a different name, also update the description and created date.

2022-07-19 22:53 UTC, dylanjm commented on tests/workshop/simple/heron_input.xml
> +    <verbosity>all</verbosity>
what's the purpose of this change? Doesn't it default to "all"?

2022-07-19 22:53 UTC, dylanjm commented on src/main.py
> +  def run_moped_workflow(self, case = None, components = None, sources = None):
remove spaces in between `=`

2022-07-19 22:53 UTC, dylanjm commented on src/main.py
> +    print("*******************************************************************************")
Probably use the message handler here and shorten the message to something like "using workflow: MOPED".

2022-07-19 22:53 UTC, dylanjm commented on src/main.py
> +    print("*******************************************************************************")
That's more of a stylistic preference on my side though. @PaulTalbot-INL might have an opinion. It shouldn't hold back merging though.

2022-07-19 22:53 UTC, dylanjm commented on src/main.py
> +from queue import Empty
what's this used for?

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +import _utils as hutils
please separate library imports in the following order and manner:

1. Internal Python modules
2. External Python modules
3. Our Python modules

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +#from TEAL.src import CashFlow as RunCashFlow
remove commented code.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        self._components = [] # List of components objects from heron input
The only time I like aligning comments to a column is in cases like this where we are listing out all the variables

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +          # clustered is better for testing and speed, full gives a more realistic NPV result
I don't like the way this comment is structured. Better to put both lines up above the eval mode.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +          # organizes important information for problem construction
Same idea as before.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        self._solver = SolverFactory('ipopt') # Solver for optimization solve, default is 'ipopt'
Perhaps add a TODO to make this specified by a user?

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        self.verbosityPrint(f'|Built activity Indicator: {activity}|')
Have this class use the MessageHandler.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        self._dispatch = [] # List of pyomo vars/params for each realization and year
You also will need to either accept a MessageHandler argument or initialize the MessageHandler inside the __init__

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        for comp in self._components:
Using `itertools.product()` would clean this code up nicely.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +                        activity.append(f'{comp.name}|Hourly_{real+1}')
Is Hourly the best word here? Our costs could potentially recur on any time-resolution right?

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +                    activity.append(f'{comp.name}|Cap')
I feel like `Capex` would be more formal here. Not sure if you are required to call it Cap tho.

2022-07-19 22:53 UTC, dylanjm commented on src/Moped.py
> +        for k,v in params.items():
use better variable names for this.

2022-07-20 14:09 UTC, PaulTalbot-INL commented on src/main.py
> +  elif sim._case._workflow == 'combined':
I don't really see a use case for it either, unless this were going to be used in a short run to determine which approach is preferable. I think if we wanted to do that, though, we wouldn't set up the full case in both workflow styles, but rather would calculate the number of degrees of freedom (or something similar). I agree this feature probably won't be used enough to be maintained.

2022-07-20 14:11 UTC, PaulTalbot-INL commented on src/main.py
> +    print("*******************************************************************************")
Hm, that's an interesting question. Since we're not using RAVEN, there's no need to use that message handler; however, HERON widely uses the message handler, so it would make sense here too. Since the message handler provides a way to manage verbosity and futureproof for logging changes, it would probably be convenient to use the RAVEN message handler.

2022-07-20 14:14 UTC, PaulTalbot-INL commented on src/Moped.py
> +                        activity.append(f'{comp.name}|Hourly_{real+1}')
good point; while in practice we often do hourly analysis, in practice we're not tied to that. Following a similar convention to HERON, perhaps we should use the same naming templates for variable names? This might be a future task.

2022-07-20 14:26 UTC, dylanjm commented on src/Moped.py
> +                        activity.append(f'{comp.name}|Hourly_{real+1}')
Yeah, I kind of like the "Macro" and "Micro" terminology but am open to anything else too.

2022-07-20 17:26 UTC, AnthoneyGriffith commented on src/Moped.py
> +import _utils as hutils
I believe I have fixed this. Please let me know if this is still incorrect on the next push

2022-07-21 14:46 UTC, dylanjm requested changes
Just small changes, and I think there might be a merge conflict with the documentation fix that just occurred.

2022-07-21 14:46 UTC, dylanjm commented on doc/user_manual/script/collect_tex.py
> +from HERON.src import Cases, Components, Placeholders
Aren't these changes already pushed to devel? This will create merge conflicts I believe.

2022-07-21 14:46 UTC, dylanjm commented on src/Moped.py
> +import itertools as it
`functools` and `itertools` are internal python modules.

2022-07-21 19:22 UTC, dylanjm commented
Closing due to some complicated git issues. New PR https://github.com/idaholab/HERON/pull/188 will replace this one.

2022-07-21 19:22 UTC, closed without merging