MOPED2
idaholab/HERON pull request #188
Opened 2022-07-21 19:17 UTC by AnthoneyGriffith

--------
Pull Request Description
--------
##### What issue does this change request address?
#186 

##### What are the significant changes in functionality due to this change request?
Allows user to select alternate workflow for optimization/analysis.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-07-21 19:21 UTC, dylanjm commented
Closing due to some complicated git issues. New PR #188 will replace this one.

2022-07-21 20:10 UTC, dylanjm requested changes, later dismissed
Some more changes to consider.

2022-07-21 20:10 UTC, dylanjm commented on src/main.py
> +from HERON.src import Moped
I think we should be able to do something like: `from HERON.src.Moped import MOPED`

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +#!/usr/bin/env python
We don't need this first line.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +import itertools as it
`functools` and `itertools` are internal python modules.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +# General access to RAVEN
You can remove this comment

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +# Access to TEAL
You can remove this comment.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +# Access to externalROMloader
You can remove this comment

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +from HERON.src.base import Base
move this next to the _utils import and make the _utils import follow the same import style

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +        from ravenframework.utils import xmlUtils
Is there a reason why you are waiting to import xmlUtils?

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +          @ In, consumes, bool, does this component consume resources
mention it Defaults to False

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +        #if isinstance(type, type(self._components[0]._produces[0])):
Remove commented code.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +              )
If you format like this you must align `)` with `self`

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +              )
Same comment as above

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +        for comp in self._components:
Just realized you are using an indent-offset of 4 for this file. The style guide requires us to use an offset of 2.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +            for cf in comp._economics._cash_flows:
I think it would be good to leave a TODO to refactor this, not worthy of preventing a merge, but the code is dense and repeats.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +            if isinstance(alpha, float):
Why does alpha being a float matter so much here?

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +                resource = prod._capacity_var
You can save some space here by not assigning resource and just doing:

```python
if prod._capacity_var not in self._resources: ...
```

Same with the next if statement.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +                        initialize=lambda m, c, t: 0,
These lines need indentation

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +                          expr = lambda m, c, t: param[(c,t)] == capacity)
this line needs indentation or put back on the previous line.

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +                          initialize = lambda m, c, t: 0,
need indentation

2022-07-21 20:10 UTC, dylanjm commented on src/Moped.py
> +                        param = pyo.Param(self._m.c, self._m.t,
indentation

2022-08-01 16:44 UTC, AnthoneyGriffith commented on src/Moped.py
> +            if isinstance(alpha, float):
This checks if alpha is an array of unique prices for each time step, or if there exists a constant price (float). Prevents the intra year method from having a shape error.

2022-08-01 16:48 UTC, AnthoneyGriffith commented on src/Moped.py
> +        from ravenframework.utils import xmlUtils
This location is not accessible to the PATH variable until the ravenROMexternal object has been initialized I believe.

2022-08-01 16:52 UTC, AnthoneyGriffith commented on src/Moped.py
> +        for comp in self._components:
Is it okay to have the indent change show up in a future PR for this feature?

2022-08-01 16:52 UTC, AnthoneyGriffith commented on src/Moped.py
> +        for comp in self._components:
I have a working branch off of this one that has fixed this indent size.

2022-08-01 17:12 UTC, PaulTalbot-INL commented on src/Moped.py
> +        from ravenframework.utils import xmlUtils
It would be great to add a comment above line 129 to that effect, since someone else will likely try to relocate it. Can you put that in your next PR?

2022-08-01 17:13 UTC, PaulTalbot-INL commented on src/Moped.py
> +        for comp in self._components:
I don't like it, but I'm okay with it. I think we have the flexibility to absorb the spacing fix until the next PR.

2022-08-01 17:13 UTC, PaulTalbot-INL commented on src/Moped.py
> +            if isinstance(alpha, float):
A comment on this would also be helpful, for the next person following up.

2022-08-02 20:36 UTC, PaulTalbot-INL requested changes
A couple little things to patch up. This is great stuff!

2022-08-02 20:36 UTC, PaulTalbot-INL commented on src/Moped.py
> +  def __init__(self):
as silly as it is, the constructor needs docstrings. In and Out are both None, and the description doesn't have to be more exciting than
```python
"""
  Construct.
  @ In, None
  @ Out, None
"""
```

2022-08-02 20:36 UTC, PaulTalbot-INL commented on src/Moped.py
> +      @ Out, capacity, np.array/pyomo.var, capacity variable for the component
I think these outs are reversed in order, no?

2022-08-02 20:36 UTC, PaulTalbot-INL commented on src/Moped.py
> +    self.raiseAMessage(f"The final NPV is: {NPV}")
These should probably output somewhere useful so the user can review them. That can come in future work, just noting this.

2022-08-02 20:36 UTC, PaulTalbot-INL commented on src/Moped.py
> +      @ In, None
there's another "in" for this method.

2022-08-03 22:22 UTC, PaulTalbot-INL commented on src/Moped.py
> +  def __init__(self):
I didn't see this still. Did it make it in?

2022-08-03 22:24 UTC, PaulTalbot-INL commented on src/Testers/HeronMopedTester.py
> +sys.path.pop()
This doesn't need changing, but most of this header can be removed since the HeronIntegration class takes care of it. If you need to change anything else on this PR, you can change this too.

2022-08-03 22:25 UTC, PaulTalbot-INL approved these changes, later dismissed

2022-08-03 22:26 UTC, PaulTalbot-INL commented
Approved for merge once tests pass without further change. Nice work!

2022-08-04 14:26 UTC, PaulTalbot-INL commented
It looks like some of your ARMAs were trained before Jacob made changes to the library use, so they'll need to be retrained and committed with the current `devel` of RAVEN.

2022-08-04 14:27 UTC, PaulTalbot-INL commented
```
  File "/home/civet/civet/build_0/raven/ravenframework/SupervisedLearning/ARMA.py", line 1391, in writeXML
    armaNode.append(xmlUtils.newNode('std', text=arma.sigma))
  File "/home/civet/miniconda3/envs/raven_libraries/lib/python3.7/site-packages/statsmodels/base/wrapper.py", line 34, in __getattribute__
    obj = getattr(results, attr)
AttributeError: 'ARMAResults' object has no attribute 'sigma'
 ... Errors were encountered while running HERON.

Running test failed with exit code 1
(22F3/27) Failed (  4.59sec)/home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/wind/Moped_wind
(23F3/27) Success(  2.26sec)/home/civet/civet/build_0/HERON/tests/unit_tests/component
(24F3/27) Success(  2.29sec)/home/civet/civet/build_0/HERON/tests/unit_tests/ValuedParams/parametric
SKIPPED ({'heavy'} is not a subset of {'normal'})
(25F3/27) Skipped(  None!  )/home/civet/civet/build_0/HERON/tests/workshop/simple/Workshop_HTSE_Simple1
SKIPPED ({'heavy'} is not a subset of {'normal'})
(26F3/27) Skipped(  None!  )/home/civet/civet/build_0/HERON/tests/workshop/wind/Workshop_Wind
(27F3/27) Success( 72.34sec)/home/civet/civet/build_0/HERON/tests/integration_tests/mechanics/multirun_sweep_opt/MultiRun_Opt
FAILED:
Failed /home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/simple/Moped_simple
Failed /home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/synthetic_cashflows/Moped_synthetic_cashflows
Failed /home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/wind/Moped_wind

PASSED: 20
SKIPPED: 4
FAILED: 3
... there were failed tests for plugin HERON!
```

2022-08-04 18:04 UTC, PaulTalbot-INL approved these changes, later dismissed

2022-08-04 18:05 UTC, PaulTalbot-INL commented
Good to merge if tests pass without further modification.

2022-08-05 03:44 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1131018/) on 1c82755 : invalidated by @dgarrett622

Try this again now that HERON and TEAL submodule updates are merged into RAVEN

2022-08-05 14:48 UTC, PaulTalbot-INL approved these changes

2022-08-05 14:49 UTC, merged