Optimized dispatches from HERON to HYBRID
idaholab/HERON pull request #202
Opened 2022-08-15 23:25 UTC by BotrosHanna-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Issue #201 : Using HERON OptimizedDispatch in HYBRID 

##### What are the significant changes in functionality due to this change request?
HERON-HYBRID Integration

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-08-15 23:32 UTC, BotrosHanna-INL commented
@PaulTalbot-INL 
Hi Paul,
Here is the (dispatches from HERON to HYBRID) PR for your comments.

2022-08-17 14:40 UTC, PaulTalbot-INL requested changes

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, text a file autoloaded with the list of components' capacities from the HERON file and placeholders for the components' capacities in HYRBID
these docstrings should be indented one more time beyond the triple quotes

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  HERON_inp_tree = ET.parse(heron_input)
This is fine for now, but we may not always use XML and we should use the RAVEN tree reader instead. We can fix that if and when we ever get that far.

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, a text file autoloaded with the optimized dispatches plus placeholders for the HYBRID dispatches
same indent needed here, 2 more spaces past the triple quotes

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, a text file autoloaded with the optimized dispatches plus placeholders for the HYBRID dispatches
also, this method doesn't look to me like it returns anything, so this should be `@ Out, None`

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, text a file autoloaded with the list of components' capacities from the HERON file and placeholders for the components' capacities in HYRBID
coming back and checking, this method also doesn't return anything, so out should be None

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +from colorama import Style
is colorama part of our standard install?

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/export2Hybrid.py
> +  @ Out, a dictionary that matches HERON and HYBRID dispatches, dict, Defining the HYBRID dispatch that corresponds to each HERON dispatch
the first argument here should be the variable name, so `heron_hybrid_dispatch` for the second output.

I know that giving the name of an output makes no sense, but them's the rules.

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/export2Hybrid.py
> +  @ Out, interesting dataset, pandas.core.frame.DataFrame, time-dependent optimized variables
the methods in this file also need docstrings indented within the triple quotes 1 more level

2022-08-17 14:40 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/tests
> +  [../]
is this missing the test to create the dispatch_print.csv?

2022-08-22 20:21 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, text a file autoloaded with the list of components' capacities from the HERON file and placeholders for the components' capacities in HYRBID
fixed it.

2022-08-22 20:22 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  HERON_inp_tree = ET.parse(heron_input)
Noted

2022-08-22 20:22 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +  @ Out, output_file, str, a text file autoloaded with the optimized dispatches plus placeholders for the HYBRID dispatches
fixed it.

2022-08-22 20:23 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/create_user_input.py
> +from colorama import Style
changed it.

2022-08-22 20:23 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/export2Hybrid.py
> +  @ Out, a dictionary that matches HERON and HYBRID dispatches, dict, Defining the HYBRID dispatch that corresponds to each HERON dispatch
fixed it.

2022-08-22 20:23 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/export2Hybrid.py
> +  @ Out, interesting dataset, pandas.core.frame.DataFrame, time-dependent optimized variables
fixed it.

2022-08-22 20:24 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/tests
> +  [../]
I added a test to create  dispatch_print.csv

2022-08-22 20:28 UTC, BotrosHanna-INL commented
@PaulTalbot-INL 

Thank you, Paul, for you comments. Let me know if I need to make more changes. I know that I still need to add this work to the user manual. I will send another message after I do it.

2022-08-22 20:34 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/tests
> +        [./dispatches2Hybrid]
Does nesting these work? I've never tried that.

2022-08-22 20:37 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/tests
> +        [./dispatches2Hybrid]
It looks like it only ran the one test:
```
...
(16/32) Success( 11.24sec)/home/civet/civet/build_0/HERON/tests/integration_tests/mechanics/var_demand_fix_price/VarDemandFixPrice
(17/32) Success( 11.86sec)/home/civet/civet/build_0/HERON/tests/integration_tests/mechanics/var_demand_var_price/VarDemandVarPrice
(18/32) Success( 11.39sec)/home/civet/civet/build_0/HERON/tests/integration_tests/mechanics/optimizedDispatch2Hybrid/DebugMode
(19/32) Success(  3.74sec)/home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/consumption/Moped_consumption
(20/32) Success( 20.24sec)/home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/simple/Moped_simple
(21/32) Success(  3.57sec)/home/civet/civet/build_0/HERON/tests/integration_tests/workflows/MOPED/storage/Moped_storage
...
```

I think you want to separate the tests, and set up prerequisites.

2022-08-22 23:09 UTC, BotrosHanna-INL commented on tests/integration_tests/mechanics/optimizedDispatch2Hybrid/tests
> +        [./dispatches2Hybrid]
Thank you! I thought that nesting the tests sets up the prerequisites and since I did not get any error messages, I thought that the RavenPython tests are successful. Now, I set up the prerequisites and I think all the tests are run now.

2022-08-23 14:10 UTC, PaulTalbot-INL submitted a review, later dismissed
LGTM

2022-08-23 14:12 UTC, PaulTalbot-INL commented
I don't see the user manual changes, but I do see the readme. Do you still have user manual changes coming?

2022-08-23 19:28 UTC, PaulTalbot-INL approved these changes, later dismissed

2022-08-23 19:44 UTC, PaulTalbot-INL submitted a review, later dismissed

2022-08-23 20:28 UTC, PaulTalbot-INL approved these changes

2022-08-23 20:28 UTC, merged