Parallel work to expand usefulness of parallel tag
idaholab/HERON pull request #205
Opened 2022-08-31 18:36 UTC by joshua-cogliati-inl

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #204 

##### What are the significant changes in functionality due to this change request?
Expands the parallel tag to allow more features.
Adds a way to just run HERON with an integration test
Adds different defaults for parallel inner and outer size.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-08-31 20:45 UTC, dylanjm requested changes

2022-08-31 20:45 UTC, dylanjm commented on tests/integration_tests/cluster_check/gold/outer.xml
> +     <clusterParameters>-P nst -j oe</clusterParameters> -->
Should we remove this commented code from the outer.xml template file now?

2022-08-31 20:48 UTC, PaulTalbot-INL commented on tests/integration_tests/cluster_check/gold/outer.xml
> +     <clusterParameters>-P nst -j oe</clusterParameters> -->
that's probably a good idea.

2022-08-31 22:27 UTC, joshua-cogliati-inl commented on tests/integration_tests/cluster_check/gold/outer.xml
> +     <clusterParameters>-P nst -j oe</clusterParameters> -->
Removed.

2022-09-01 14:04 UTC, dylanjm approved these changes
Changes look good. New feature is documented.

FUTURE WORK IDEA: Add use-case examples walkthroughs to the wiki, one for local, one for HPC. Also a debugging workflow.

2022-09-01 16:18 UTC, merged