HERD - HERON Runs DISPATCHES
idaholab/HERON pull request #213
Opened 2022-09-28 21:52 UTC by GabrielSoto-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
#212 

##### What are the significant changes in functionality due to this change request?
New workflow option, in addition to the 'standard' and 'MOPED' workflows, for running a DISPATCHES multiperiod optimization using an existing DISPATCHES nuclear flowsheet. The flowsheet uses IDAES Pyomo models to represent a nuclear plant with creation, storage, and combustion of hydrogen through a PEM electrolyzer, hydrogen tanks, and hydrogen turbine respectively.  Test XML scripts are included with components that match the nuclear flowsheet. A new class called HERD has been added to facilitate creation of TEAL cash flows, Pyomo constraints and DISPATCHES multiperiod methods. HERD checks that components from XML input match the nuclear flowsheet before simulation. Documentation has been added to the HERON user manual as well as docstrings for all methods. Relevant testing also added. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-09-29 00:00 UTC, dylanjm commented
Looks like you have a sour import setup going on with the dispatches module:

```
Traceback (most recent call last):
  File "/home/civet/civet/build_0/HERON/src/main.py", line 19, in <module>
    from HERON.src import Herd
  File "/home/civet/civet/build_0/HERON/src/../../HERON/src/Herd.py", line 26, in <module>
    from dispatches.case_studies.nuclear_case.nuclear_flowsheet import build_ne_flowsheet
ModuleNotFoundError: No module named 'dispatches'
 ... Errors were encountered while running HERON.
```

2022-09-29 21:18 UTC, dylanjm requested changes

2022-09-29 21:18 UTC, dylanjm commented on tests/integration_tests/workflows/HERD/nuclearCase_notebook_match/dispatches_input.xml
> +    <ARMA name='LMP' variable="TOTALLOAD">%HERON%/tests/workshop/arma_202112_nyiso_def.pk</ARMA>
As a heads up, in another PR I currently have submitted I am deleting this `pk` file and replacing all the paths with:

```
%HERON%/tests/integration_tests/ARMA/NYISO/nyiso_arma_2yr.pk
```

2022-09-30 16:55 UTC, dylanjm requested changes
Really good for your first major PR. I just have some minor formatting requests. I will take another deeper look next revision.

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +dispatches_model_component_meta={
Since this is a global variable, I like to distinguish them by using all-caps SNAKE_CASE. This makes it easier to see when it's used in local scope.

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +  def _setTestTimeSets(self):
I really dislike the way it's been setup but in HERON we use snake_case convention for variables and function names. We only use camelCase when we are using RAVEN specific methods.

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +      raise IOError('MOPED does not currently support sweep values option')
I think `MOPED` needs to be changed to `HERD`

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +      @In: ps: Pyomo model for period within a given scenario
Reformat the `@In:` to `@In, `

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +      @In: ps: Pyomo model for period within a given scenario
Also still specify `@Out, None` if it doesn't return anything.

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +                          doc="Maximum capacity of the PEM electrolyzer (in kW)")
I believe the hanging lines should be indented to line up with `within` See https://legacy.python.org/dev/peps/pep-0008/#indentation

2022-09-30 16:55 UTC, dylanjm commented on src/Herd.py
> +                        doc="Design PEM capacity (in kW)")
vertical alignment

2022-09-30 16:55 UTC, dylanjm commented on src/main.py
> +  def run_dispatches_workflow(self, case = None, components = None, sources = None):
I realize this is probably recreated from the other methods here, but I truly wonder why we have these arguments here. Do we ever plan to divorce the the template parsing from the execution of the workflow? Shouldn't these methods pretty much always resort to using `self._case/components/sources`?

2022-09-30 16:55 UTC, dylanjm commented on tests/integration_tests/workflows/HERD/nuclearCase_Sine/dispatches_sine_input.xml
> +    <!--<ARMA name='Load' variable="TOTALLOAD">../arma_202112_nyiso_def.pk</ARMA>-->
Is this still required? Remove if not.

2022-09-30 16:55 UTC, dylanjm commented on tests/integration_tests/workflows/HERD/nuclearCase_notebook_match/dispatches_input.xml
> +    <ARMA name='dispatches-test' variable="TOTALLOAD">%HERON%/tests/workshop/arma_202112_nyiso_def.pk</ARMA>
You'll need to change this path now to the previous comment I made.

2022-09-30 17:09 UTC, GabrielSoto-INL commented on tests/integration_tests/workflows/HERD/nuclearCase_notebook_match/dispatches_input.xml
> +    <ARMA name='LMP' variable="TOTALLOAD">%HERON%/tests/workshop/arma_202112_nyiso_def.pk</ARMA>
filepath has been updated

2022-09-30 17:15 UTC, PaulTalbot-INL commented on src/Herd.py
> +  def _setTestTimeSets(self):
I don't think you have to, per se; the intent is to be more pep8-y in HERON than RAVEN requires

2022-09-30 17:23 UTC, dylanjm commented on src/Herd.py
> +  def _setTestTimeSets(self):
Agreed, if it's a huge pain to change them or you feel strongly about it, no worries.

2022-09-30 17:39 UTC, GabrielSoto-INL commented on src/main.py
> +  def run_dispatches_workflow(self, case = None, components = None, sources = None):
I can't speak to the standard or MOPED workflows, but the DISPATCHES workflow will use template parsing/XML inputs for the foreseeable future. I can remove those arguments from the `run_dispatches_workflow` method and avoid the subsequent `if-else` statements (but keep the `assert`)

2022-09-30 18:46 UTC, GabrielSoto-INL commented on src/Herd.py
> +  def _setTestTimeSets(self):
I changed all new HERD-specific variable and function names

2022-09-30 19:08 UTC, dylanjm commented on src/main.py
> +  def run_dispatches_workflow(self, case = None, components = None, sources = None):
Yeah that sounds good.

2022-10-03 12:24 UTC, GabrielSoto-INL commented
All current comments have been addressed, PR is ready for another look

2022-10-10 03:27 UTC, dylanjm approved these changes
Changes look good to me. Might be worth to send an email out to the user group about this new feature. @PaulTalbot-INL Thoughts on this?

2022-10-10 16:12 UTC, merged

2022-10-10 17:03 UTC, PaulTalbot-INL commented
Just for bookkeeping, I noted to Dylan that I don't think we have a lot of traction on the user list, so putting a note on the discussion board may be more useful.