Work on making a pip installable HERON package.
idaholab/HERON pull request #216
Opened 2022-10-11 20:58 UTC by joshua-cogliati-inl

--------
Pull Request Description
--------
##### What issue does this change request address?

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-10-12 21:42 UTC, joshua-cogliati-inl commented
Requires https://github.com/idaholab/raven/pull/1994

2022-10-13 18:53 UTC, dylanjm commented on src/_utils.py
> +  try:
I found that this method gets called repeatedly in the `DispatchManager.py` for each ARMA realization. I was able to reduce quite a significant amount of memory consumption by memoizing this function. Instead of making a whole new PR, it might be worth to just add here. All you need to do is:

at the top in the imports:
```python3
from functools import cache
```

and then add the decorator to the function:

```python3
@cache
get_synthhist_structure
```

2022-10-13 19:01 UTC, PaulTalbot-INL commented on src/_utils.py
> +  try:
ohhh, because RAVEN runs this each time instead of once ever ... maybe Mohammad's work will fix this to some degree. Good catch.

2022-10-13 19:19 UTC, joshua-cogliati-inl commented on src/_utils.py
> +  try:
Thanks, fixed: 764ce1c

2022-10-13 19:27 UTC, joshua-cogliati-inl commented on src/_utils.py
> +  try:
I am pretty should this cache is per process, so non-shared memory parallelism would have to cache it multiple times.

2022-10-13 19:31 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1201486/) on 764ce1c : invalidated by @joshua-cogliati-inl

Updated RAVEN to add ravenframework.ROMExternal

2022-10-13 20:10 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +#from pyutilib.common._exceptions import ApplicationError
Commented code can be removed.

2022-10-13 20:13 UTC, dylanjm requested changes
Just one change and one question. Otherwise changes look good to me.

2022-10-13 20:13 UTC, dylanjm commented on tests/integration_tests/workflows/production_flex/heron_input.xml
> +    <ARMA name='Price' variable="Signal">%BASE_WORKING_DIR%/../../../ARMA/Sine/arma.pk</ARMA>
Curious about the purpose this change.

2022-10-13 20:15 UTC, joshua-cogliati-inl commented on tests/integration_tests/workflows/production_flex/heron_input.xml
> +    <ARMA name='Price' variable="Signal">%BASE_WORKING_DIR%/../../../ARMA/Sine/arma.pk</ARMA>
Basically, this is for testing heron from a pip install, and in a pip install, %HERON% may not be anywhere near the tests directory, so I changed it to be relative to the base working directory.  At some point all the tests will have to be changed to do this.

2022-10-13 20:24 UTC, joshua-cogliati-inl commented on tests/integration_tests/workflows/production_flex/heron_input.xml
> +    <ARMA name='Price' variable="Signal">%BASE_WORKING_DIR%/../../../ARMA/Sine/arma.pk</ARMA>
So after HERON is pip installed, we can:
```
cd tests/integration_tests/workflows/production_flex
heron heron_input.xml
raven_framework outer.xml
```

2022-10-13 20:38 UTC, dylanjm approved these changes
Changes look good and don't affect major functionality.

2022-10-13 21:05 UTC, merged