Resourcegraph
idaholab/HERON pull request #223
Opened 2022-11-02 15:05 UTC by dylanjm

--------
Pull Request Description
--------
##### What issue does this change request address?

#163

##### What are the significant changes in functionality due to this change request?

This PR implements the ability to create a resource graph png during a debug mode run

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [x] 4. Automated Tests should pass.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [x] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [x] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [x] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [x] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2022-11-02 15:54 UTC, dylanjm commented
Here is what the plots look like:

![image](https://user-images.githubusercontent.com/15963026/199537841-dbdafc92-2e3a-465b-95aa-c4261c2cb20e.png)

2022-11-02 17:01 UTC, PaulTalbot-INL commented on src/main.py
> +  sim.plot_resource_graph()
This might be fine initially, but I think this network graph should be something we do at the HERON compilation stage instead of during dispatch optimization. How hard would it be to move?

2022-11-02 17:11 UTC, dylanjm commented on src/main.py
> +  sim.plot_resource_graph()
I believe this is creating the plot during HERON compilation. If debug mode is enabled it will create the plot when running `heron heron_input.xml`

2022-11-02 17:19 UTC, PaulTalbot-INL commented on src/main.py
> +  sim.plot_resource_graph()
Oh, you're right, I'm sorry. I saw  `sim.print_me()` and immediately thought of the pyomo model. I should have looked more closely! I'm still on travel but can review this tomorrow or Friday probably.

2022-11-02 17:32 UTC, dgarrett622 requested changes
This looks like a cool addition. The code looks good, I did have one comment on the function annotations. The only thing I think is missing is a test case.

2022-11-02 17:32 UTC, dgarrett622 commented on src/NetworkPlot.py
> +  def __init__(self, components: list) -> None:
I see you added annotations to method definitions (-> and the like). It is PEP compliant (3107) and I think it adds some valuable information, especially to developers at a quick glance. I haven't seen these annotations elsewhere in HERON, should we standardize this practice going forward? What I mean is, should we include these annotations going forward or remove them? I would vote for including them.

2022-11-02 17:43 UTC, dylanjm commented on src/NetworkPlot.py
> +  def __init__(self, components: list) -> None:
Yes, I agree. I like having the annotations and the more detailed we can be with them, the more easy our code would be to understand. Perhaps maybe a soft encouragement to use them going forward? We could easily add a pylint type checking test to our Precheck on CIVET if we wanted to make it a hard standard. @PaulTalbot-INL @joshua-cogliati-inl  do you have any specific ideas or reservations about this?

2022-11-02 19:11 UTC, PaulTalbot-INL commented on src/NetworkPlot.py
> +  def __init__(self, components: list) -> None:
I am not ready to codify it as required practice, but I certainly am happy to see it added where possible. If forced into a decision, I would prefer to include them, but it will take time and opportunity to convert existing code to this standard. I would also like to re-think the RAVEN approach to docstrings at the same time, since this info is largely included in the type hints, but that represents a significant change for a lot of code, possibly.

2022-11-02 19:24 UTC, joshua-cogliati-inl commented on src/NetworkPlot.py
> +  def __init__(self, components: list) -> None:
I am okay with optionally adding typing annotations.  We should add checking them with mypy or pyright or similar before making them required.

2022-11-07 18:42 UTC, PaulTalbot-INL commented
@dgarrett622 are you available to finish the review of this PR?

2022-11-07 19:25 UTC, dgarrett622 approved these changes

2022-11-07 19:28 UTC, dgarrett622 commented
Everything looks good to go. I'll get this merged in momentarily. Thanks @j-bryan and @dylanjm!

2022-11-07 19:28 UTC, merged