Meta bug
idaholab/HERON pull request #26
Opened 2020-09-24 18:18 UTC by dhill2522

--------
Pull Request Description
--------
##### What issue does this change request address?
This addresses a bug where `meta` would become nested when using a component producing via a transfer function. A unit test has been added to test for nested `meta` dicts as well. 

##### What are the significant changes in functionality due to this change request?
- Meta no longer nests when "producing" with a transfer function
- A `HeronPython` tester that subclasses `RavenTester` is implemented for running unit tests
- The first unit test is added

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2020-09-24 18:19 UTC, dhill2522 commented
I am just trying to figure out why the new `validator` integration test is failing on my branch before allowing this to be merged.

2020-09-24 18:23 UTC, dhill2522 commented
@PaulTalbot-INL I was a little unsure about the best naming scheme for the files and variables as well as how fine you would like to divide up your tests. Please let me know if you would prefer things to be named differently. 

For example I was not sure if the unit test file should be named something as broad as `testComponent.py` or if I should be highly specific with something like `testMetaNesting.py`.

2020-09-24 18:50 UTC, dhill2522 commented
@PaulTalbot-INL Do you have any idea why the `validator` test may be failing for this PR? The test appears to have run fine, but it gives a `DIFF` error for some reason. When I diff the files manually they appear to be the same, just with the columns in a different order. 

The test also fails for me even when I am on `devel`.

2020-09-24 19:05 UTC, PaulTalbot-INL commented
Ah, columns in a different order is enough to fail a OrderedCsv test; is the Validator Ordered? Also, I wonder why the order of the columns is changing ...

2020-09-24 19:12 UTC, PaulTalbot-INL reviewed
A couple comments to address.

2020-09-24 19:12 UTC, PaulTalbot-INL commented on src/Components.py
> +    inputs['dispatch'] = dispatch
I'm working on changing `meta` to a `SystemState` object in a feature branch, FYI; this is a good stopgap.

2020-09-24 19:12 UTC, PaulTalbot-INL commented on src/Testers/HeronPythonTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, '..', 'heron')
do we use the executable for the unit test?

2020-09-24 19:12 UTC, PaulTalbot-INL commented on tests/unit_tests/testComponent.py
> +# Make the production request
I would add more comments here about exactly what is being tested; this testComponent will very likely be extended to test a variety of things in the future.

This will allow you to update this file's docstrings to be more general, as well.

2020-09-24 19:12 UTC, PaulTalbot-INL commented on tests/unit_tests/testComponent.py
> +sys.exit(0)
I would recommend setting up a tracking system like in the `raven` unit tests for pass and fail, and existing with the fail value, so that we can chain together unit tests for `Component` objects in this file. Great work!

2020-09-24 19:12 UTC, PaulTalbot-INL commented on src/Testers/HeronPythonTester.py
> +class HeronPython(RavenTester):
Is this distinct from the `RavenPython` tester in a meaningful way? I'm okay with keeping it if we think we'll leverage a python unit testing framework or something in the future; otherwise, let's limit the redundancy so RAVEN can maintain the code.

2020-09-24 23:04 UTC, dhill2522 commented on src/Components.py
> +    inputs['dispatch'] = dispatch
Sounds good. I feel like an object would work a lot better here for state passing than a dict. It would probably help end users with transfer functions that need to access the system state.

2020-09-24 23:18 UTC, dhill2522 commented on src/Testers/HeronPythonTester.py
> +class HeronPython(RavenTester):
That's a good point. I had assumed that we would need this as we need to change the command to directly run the python test files instead of running input xml files as it appears the `RavenFramework` tester does.

As far as I can tell the `RavenFramework` tester generates a command in the form of `python Driver.py input.xml` while `HeronTester` generates a command in the form of `python testMe.py`. This allow us to write our test directly in Python and have full access to the internal state.

My hope was that we would be able to test very specific parts of the framework with a python tester and dodge having full xml inputs for each unit test.

Please correct me if I am wrong.

2020-09-24 23:19 UTC, dhill2522 commented on tests/unit_tests/testComponent.py
> +sys.exit(0)
I like that idea. I will go ahead and add that once I get a chance.

2020-09-24 23:20 UTC, dhill2522 commented on src/Testers/HeronPythonTester.py
> +    self.heron_driver = os.path.join(HERON_LOC, '..', 'heron')
Nope, thanks for catching that! I'll remove it.

2020-09-24 23:21 UTC, dhill2522 commented on tests/unit_tests/testComponent.py
> +# Make the production request
Sounds good. Will do.

2020-09-25 21:59 UTC, dhill2522 commented
@PaulTalbot-INL I have no idea why the order changes or why the validator cares. As far as I can tell, HERON validators default to unordered and that does not seem to be overridden in the `Example` validator.

 More importantly I can't get the `validator` integration test to pass in the devel branch either. I have tried it on multiple machines at this point.

Any thoughts about what might be going on here? Do all the tests for my branch pass on your machine?

2020-09-28 14:17 UTC, PaulTalbot-INL commented on src/Testers/HeronPythonTester.py
> +class HeronPython(RavenTester):
Ah, `RavenFramework` and `RavenPython` testers are distinct. `RavenFramework` runs `raven` on an `xml` file, while `RavenPython` runs `python` and checks return status.

2020-09-28 14:27 UTC, dhill2522 commented on src/Testers/HeronPythonTester.py
> +class HeronPython(RavenTester):
Ok, somehow I had missed the existence of `RavenPython`. I will go ahead and switch over to using that instead as long as it works. Thanks for catching that!

2020-09-28 14:41 UTC, dhill2522 commented on src/Testers/HeronPythonTester.py
> +class HeronPython(RavenTester):
I just removed the `HeronPython` tester. Considering this resolved.

2020-09-28 15:40 UTC, PaulTalbot-INL commented
I tried running the Validator test again, and on RAVEN devel and HERON devel, it passed 5/5 times. This is on a mac; what OS are you testing on?

We are hoping to have `civet` connected again soon and can run our automated tests; `civet` is up but we're getting timeout responses from it right now.

2020-09-28 15:59 UTC, dhill2522 commented
I tested it on two different Fedora machines. I'll try and see if we can test on Mac and Windows machines today in case it is somehow an OS-related issue.

2020-09-29 23:15 UTC, dhill2522 commented
Just did a fresh install again on an Ubuntu machine and a Mac. The `validator` test passed on the Mac, but failed on Ubuntu. Not sure exactly what is going on here, but hopefully getting CIVIT back up will shed some light on it.

2020-09-30 14:19 UTC, PaulTalbot-INL commented
Okay, this is interesting. I did notice there were some fairly right numerical tolerances, which can vary significantly between Mac (which can use the mkl libraries) and various Linux (which can't).

Is the diff only the changed ordering of the columns? If you change the test from csv to unordered csv does it pass?

2020-09-30 15:22 UTC, dhill2522 commented
So I think I may have found the problem. Under the validator `tests` file the output is specified as being `Sweep_Runs_o/sweep.csv`, but as far as I can tell the compared output is actually `Sweep_runs_o/sweep.csv`. Note the lowercase 'r'. 

I'm not sure how this was passing on MacOS (maybe the new Z shell?), but Linux certainly does not correct the path and fails to find the CSV comparison file entirely. Once I rename the folder ('r' -> 'R') the test passes without a problem.

I'll go ahead and just commit that folder rename and I think we should be good for a review.

2020-09-30 16:59 UTC, PaulTalbot-INL requested changes
Only one minor change.

2020-09-30 16:59 UTC, PaulTalbot-INL commented on tests/unit_tests/testComponent.py
> +print('Meta after production:', meta)
Do you want to keep these print statements? They seem more like debugging options than part of the test.

2020-09-30 16:59 UTC, PaulTalbot-INL commented on tests/unit_tests/testComponent.py
> +producer._transfer._obj.evaluate = transfer_function
There definitely should be a better way to do this in the future, that involves less access of underscored variables. This is fine for now.

2020-09-30 17:56 UTC, dhill2522 commented on tests/unit_tests/testComponent.py
> +producer._transfer._obj.evaluate = transfer_function
Agreed. Certainly let me know if you are aware of a better way.

2020-09-30 17:58 UTC, dhill2522 commented on tests/unit_tests/testComponent.py
> +print('Meta after production:', meta)
It appears that the testing framework does not print any data from the tests unless it fails. I had intended these to print in the event that the test failed, allowing easy visualization of how the meta object changed.

I am happy with keeping or removing them depending on what you are looking for.

2020-09-30 18:05 UTC, PaulTalbot-INL commented on tests/unit_tests/testComponent.py
> +print('Meta after production:', meta)
Ok, that's fine. We certainly have some that are more verbose.

I'm running this locally for testing.

2020-09-30 18:05 UTC, PaulTalbot-INL approved these changes

2020-09-30 18:07 UTC, dhill2522 commented
Sounds good. I will go ahead and create a issue and link it then.

2020-09-30 18:10 UTC, PaulTalbot-INL commented
![Screen Shot 2020-09-30 at 12 09 24 PM](https://user-images.githubusercontent.com/2044370/94723349-d785d180-0315-11eb-8302-95cde380cefb.png)

2020-09-30 18:10 UTC, PaulTalbot-INL commented
Congratulations on the first HERON test running in under 1 second.

2020-09-30 18:15 UTC, dhill2522 commented
This PR closes issue #32

2020-09-30 18:17 UTC, PaulTalbot-INL commented
> This PR closes issue #32

I think this has to be in a commit message or the PR description. I'll add it there.

2020-09-30 18:18 UTC, dhill2522 commented
Ah, OK. I've never linked a PR before on GitHub. Thanks!

2020-09-30 18:19 UTC, PaulTalbot-INL commented
Checklists pass; merging.

2020-09-30 18:20 UTC, merged