Workbench integration
idaholab/HERON pull request #268
Opened 2023-03-03 21:21 UTC by lefebvrera

--------
Pull Request Description
--------
##### What issue does this change request address?
This addresses #259

##### What are the significant changes in functionality due to this change request?
A new command line option `--definition` emits the HERON input schema in a format compatible with the NEAMS Workbench.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-03-03 21:24 UTC, lefebvrera commented
@dylanjm I see a precheck has failed but I am unable to determine why. Can you assist me?

2023-03-03 21:55 UTC, dylanjm commented
@lefebvrera looks like the following files contain trailing whitespaces somewhere:

```
	src/input_definition.py
	src/main.py
```

2023-03-03 22:43 UTC, dylanjm commented
@lefebvrera looks like there is still trailing whitespace in `src/input_definition.py` There are usually some editor extensions or features that should remove these white spaces.

2023-03-06 19:11 UTC, dylanjm requested changes
All the changes look good to me, just a minor request to change doc strings to match our developer style guide.

2023-03-06 19:11 UTC, dylanjm commented on src/input_definition.py
> +    """Obtain an indent prefix whitespace string"""
Can you modify the docstrings to match our developer style for the rest of HERON? Usually they might look something like this:

```python
def indent(level):
"""
  Obtain an indent prefix whitespace string.
  @ In, int, the number of indentation levels to use.
  @ Out, indent, the resultant indentation
"""
...
```

2023-03-07 16:41 UTC, lefebvrera commented on src/input_definition.py
> +    """Obtain an indent prefix whitespace string"""
@dylanjm I updated all doc strings in input_definition.py to reflect this standard. Let me know if any further changes are needed.

2023-03-07 17:35 UTC, dylanjm submitted a review, later dismissed
A few minor changes, mostly my fault for not correctly explaining the doc string formatting.

2023-03-07 17:35 UTC, dylanjm commented on src/input_definition.py
> +      @ In, int, the number of indentation levels to use.
Sorry this line should be formated as `@ In, level, int, the number of indentation levels to use`

The next line should `@ Out, indent, str, the resultant indentation`

2023-03-07 17:35 UTC, dylanjm commented on src/input_definition.py
> +       @ In, int, the number of indentation levels to use for this component.
Since this isn't a `@classmethod` can you provide a doc string definition for `cls`. Also if a function does not return anything please add `@ Out, None`

2023-03-07 17:35 UTC, dylanjm commented on src/input_definition.py
> +    @ In, the occurrence restriction for this component
Sorry, I realized in my example I forgot to include variable names for the definition. 

So in this case it would be `@ In, occurs, bool(?), ...`

2023-03-07 17:35 UTC, dylanjm commented on src/input_definition.py
> +    @ Out, the SON-formatted input requirements
I think technically this function doesn't return anything so it should be `@ Out, None`

2023-03-07 17:35 UTC, dylanjm commented on src/input_definition.py
> +    print (indent(level+1),"Description=\""+cls.description.replace("\n"," ") \
There are spaces after `print` in a few places in this file.

2023-03-07 21:34 UTC, lefebvrera commented on src/input_definition.py
> +    print (indent(level+1),"Description=\""+cls.description.replace("\n"," ") \
@dylanjm I'm not certain what you mean by "spaces after `print`". I don't see any spaces 'after' the `print` statement.

2023-03-07 21:35 UTC, lefebvrera commented on src/input_definition.py
> +       @ In, int, the number of indentation levels to use for this component.
Done.

2023-03-07 21:35 UTC, lefebvrera commented on src/input_definition.py
> +    @ In, the occurrence restriction for this component
This should be done too.

2023-03-07 21:54 UTC, dylanjm commented on src/input_definition.py
> +    print (indent(level+1),"Description=\""+cls.description.replace("\n"," ") \
I'm specifically talking about `print (...)` vs. `print(...)`

2023-03-07 21:59 UTC, lefebvrera commented on src/input_definition.py
> +    print (indent(level+1),"Description=\""+cls.description.replace("\n"," ") \
:facepalm:. I see it now. Fixed it. Thanks for your patience.

2023-03-09 21:33 UTC, lefebvrera commented
@dylanjm I believe I have addressed your comments. Is anything remaining on this PR before we merge?

2023-03-09 22:35 UTC, PaulTalbot-INL commented
@dylanjm is away, but I can finish the review. Checklists pass, comments are addressed, and tests clear. Merging. Thanks for your work!

2023-03-09 22:35 UTC, PaulTalbot-INL approved these changes

2023-03-09 22:36 UTC, merged