Levelized Price of Resource Metric in HERON
idaholab/HERON pull request #301
Opened 2023-06-13 18:51 UTC by GabrielSoto-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
#300 

##### What are the significant changes in functionality due to this change request?
HERON now allows users to select Levelized Cost as a metric calculated in the inner optimization step. Can be selected as an optimization metric in `opt` mode or an economic metric in `sweep` mode.

- Levelized Cost is calculated via TEAL's NPV_search metric
   - this finds a multiplier on a cashflow which results in NPV equal to some target
   - the multiplier here is a cost or price, the target NPV is 0 -> this results in break-even price of a resource
   - Users can specify a nonzero target if desired, but would result in something different from "levelized cost"
- Levelized Cost is selected either within 
   - `<optimization_settings>` as `<opt_metric>LC</opt_metric>`
   -  or `<EconMetrics>` as `<LC/>`
   - optional `target` parameter for NPV target (defaults to 0, meaning it finds the cost multiplier which makes 
- User must specify which cashflow contains the levelized cost
   -  applied as a node within the `<reference_price>` node, replacing a ValuedParam entry
   - currently only available for:
      - **Demanding** components
      - **Recurring Hourly** cash flows
   - `mult_target` parameter is now deprecated
- Levelized Cost requires a different inner objective function that is automatically applied. It is nonlinear, so Levelized Cost only works currently with the `IPOPT` solver

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-06-13 20:29 UTC, PaulTalbot-INL commented on src/Cases.py
> +from collections import OrderedDict
Correct me if I'm wrong; recent versions of Python have standardized their `dict` to behave as an `OrderedDict`, by default preserving key order as added to the dictionary. Is there something else in particular we need out of `OrderedDict`, or is this just mitigating risk that someday the ordered nature may change?

2023-06-13 20:32 UTC, PaulTalbot-INL commented on src/Cases.py
> +  #    NOTE: might be important to index the stats_metrics_mapping... does VaR of IRR make sense?
Hm. "Internal Rate of Return at Risk" might be a niche but possibly interesting metric. Not sure what to think here, either. I certainly would not be surprised to see someone want to do "Levelized Cost of Hydrogen at Risk", which I guess would be more like "Xth Percentile LCOH" from a stats view.

2023-06-13 20:58 UTC, dylanjm commented on src/Economics.py
> +  def get_price(self):
Minor thought. Should we move away from explicit getters and setters in our class structures and leverage the `@property` decorator. I suppose it doesn't really matter.

2023-06-13 21:00 UTC, GabrielSoto-INL commented on src/Cases.py
> +from collections import OrderedDict
I've seen examples online where even though the standard `dict` in Python preserves order, other tools like Pandas might ignore order unless they see an `OrderedDict`. It's a "better safe than sorry" measure that I got into a habit of taking. 

The reason I want an `OrderedDict` is because I want to insert an entry at the front of the list (an optimization metric in front of a list of the other economic metrics requested) so that it gets presented first in the final CSV

2023-06-13 21:01 UTC, GabrielSoto-INL commented on src/Economics.py
> +  def get_price(self):
I'm all for an alternative that looks cleaner! I'll look into it

2023-06-13 21:03 UTC, GabrielSoto-INL commented on src/Cases.py
> +  #    NOTE: might be important to index the stats_metrics_mapping... does VaR of IRR make sense?
Yeah, I feel like the percentile would make more sense for IRR but at the moment I think I'm leaning towards just leaving the stats metrics as is, leaving the decision for the user to make.

2023-06-13 21:40 UTC, PaulTalbot-INL commented on src/Economics.py
> +  def get_price(self):
I've used it in a couple places, it's kind of fun, I don't know what the difference in cleanliness or maintainability is. No issue either way for me.

2023-06-13 21:44 UTC, PaulTalbot-INL commented on src/Cases.py
> +    use_levelized_inner = False
maybe I'm turned around; aren't we using levelized inner if we get here? Am I misunderstanding this var name?

2023-06-13 21:47 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # TODO: allow Producers and Storage later; will need to check "dispatchable"
What happens if they aren't dispatchable? Can we not still find breakeven prices on static behaviours? Oh, but we wouldn't use that as an "inner" objective in that case, we'd still max NPV and then do LC after inner dispatch opt, right?

2023-06-13 21:49 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # TODO: what happens if they are NOT a variable? a time series or fixed value?...
I have this question too; we're solving for `alpha`, why do we care where `D` comes from (to use the cashflow equation variables)?

2023-06-13 21:49 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # TODO: Should we allow them to be valued params?...
Same question, as long as it doesn't touch `alpha`, does this matter?

2023-06-13 21:51 UTC, PaulTalbot-INL commented on src/Cases.py
> +      @ Out, nametype, str, economic metric name to use (options: 'output' or 'TEAL')
Needs an ` optional,` after `str,`.

2023-06-13 21:51 UTC, PaulTalbot-INL commented on src/Cases.py
> +      @ Out, nametype, str, economic metric name to use (options: 'output' or 'TEAL')
whoops, got the wrong line, I meant to say the Input should not be None anymore.

2023-06-13 21:53 UTC, PaulTalbot-INL commented on src/Components.py
> +      TODO could this just return the only non-empty one, since there can only be one?
Shortly after splitting Component and Interaction we decided unofficially that one Interaction is enough for any Component, so practically yes but technically no.

2023-06-13 21:55 UTC, PaulTalbot-INL commented on src/Economics.py
> +      self._set_fixed_param('_alpha', 1)
Would this be a good spot to figure out what to do when `alpha` is _not_ 1? Are we reporting a scalar multiplier or `alpha` total when we report the LC metric?

2023-06-13 21:56 UTC, PaulTalbot-INL commented on src/ValuedParams/Activity.py
> +### ACCESSORS ###
Thank you, I'm incredibly lazy about these.

2023-06-13 21:58 UTC, PaulTalbot-INL commented on src/dispatch/Dispatcher.py
> +      non_multiplied_comp = 0
is it a comp or a cashflow? Either way, could we add a note around these two variables to clarify how you're setting up the objective function? I had to read through Aaron's version of this a dozen times before it finally clicked.

2023-06-13 22:00 UTC, PaulTalbot-INL reviewed
Not a formal review per se, just noting I'm done looking through what's here so far.

2023-06-14 12:34 UTC, GabrielSoto-INL commented on src/Cases.py
> +    use_levelized_inner = False
Not necessarily - I'm setting up for Levelized Cost of Capital (and Levelized Fixed Cost, I guess?) for which I think we can still use the previous inner objective. This will find the multiplier on the price per capacity, so we can still do the inner optimization as before with whatever recurring hourly prices the user provided. I might just do a check to see if the driver is a capacity rather than an activity...

2023-06-14 12:41 UTC, GabrielSoto-INL commented on src/Cases.py
> +    # TODO: allow Producers and Storage later; will need to check "dispatchable"
exactly! we can still find a breakeven price, the question is whether we should switch the inner objective functions. In that case, we keep the default inner objective - marginal hourly cashflows for dispatches that are actually variables AND we have prices for them that aren't being optimized in the outer objective

2023-06-14 12:47 UTC, GabrielSoto-INL commented on src/Cases.py
> +    # TODO: what happens if they are NOT a variable? a time series or fixed value?...
this will just determine whether we switch the inner objective function. at this stage, we are asking: will this particular cashflow show up in the inner objective function? If we're trying to find the breakeven price of a cashflow but the driver is static (i.e., NOT a variable of the inner optimization problem), it's not going to show up in the inner objective so we can use the default objective function. If the driver is an activity/dispatch, we should switch to the levelized version of the inner objective.

2023-06-14 12:49 UTC, GabrielSoto-INL commented on src/Cases.py
> +    # TODO: what happens if they are NOT a variable? a time series or fixed value?...
clarification: I plan on removing the error, and just having `use_levelized_inner ` stay `False`

2023-06-14 12:52 UTC, GabrielSoto-INL commented on src/Cases.py
> +    # TODO: Should we allow them to be valued params?...
for this one, I was worried about nonlinearity but that ship has sailed. Only weird situation I can think of is if reference driver and/or scaling factor are selected to be variables?...

2023-06-14 12:58 UTC, GabrielSoto-INL commented on src/Components.py
> +      TODO could this just return the only non-empty one, since there can only be one?
makes sense! actually though, I may have copy-pasted that from a different method...  fixing it now!

2023-06-14 13:30 UTC, GabrielSoto-INL commented on src/Economics.py
> +      self._set_fixed_param('_alpha', 1)
In the `set_reference_price( )` method, I have it set up where the user can provide both a `<levelized_cost>` node AND a valued param (e.g., ARMA). With this set up, what we report back is just the scalar multiplier on the time variant price. Chose to do it this way because reporting `alpha` total would be messy if it is time variant (in the CSV, the column reads `LC_mult`)

2023-06-14 13:32 UTC, GabrielSoto-INL commented on src/dispatch/Dispatcher.py
> +      non_multiplied_comp = 0
it's meant to be the sum of cashflows per comp, split between the multiplied and non-multiplied terms. I agree it's not super clear at first glance, I'll add some more comments to clarify

2023-06-22 20:22 UTC, PaulTalbot-INL requested changes
A few minor changes to consider.

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/Cases.py
>                          of economic metrics for all realizations. Currently only features ``NPV''. """
Is this description still accurate? It looks like you can request other metrics now besides `NPV` right?

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/Cases.py
>                            objective in the ``outer'' optimization.
Could we expand this description to add clarity? I'm not sure how to do it, but something to clarify that this is specifying which statistic of the economic metric should be used in the analysis.

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/Cases.py
>        @ In, None
can you update the inputs docstring as well?

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/Economics.py
>                for NPV matching analyses.""")
Can we note the new way this should be specified in this description?

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/Economics.py
> +      @ Out, scale, ValuedParam, valued param for
hanging "for" on each of these accessors?

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/dispatch/Dispatcher.py
> +      #print(f'DEBUGG ... comp {comp.name}')
these prints can be removed, unless you want to keep them for the future

2023-06-22 20:22 UTC, PaulTalbot-INL commented on src/dispatch/Dispatcher.py
> +        #print(f'DEBUGG ... ... time {t}')
removable

2023-06-22 20:22 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +        opt_path_plot_vars.text = opt_path_plot_vars.text.replace('mean_NPV', new_opt_objective)
Is this always the mean NPV?

2023-06-22 20:22 UTC, PaulTalbot-INL commented on tests/integration_tests/mechanics/levelized_cost/LC_Price/heron_input__LC_Price.xml
> +      <ProjectTime>20</ProjectTime>
could we reduce the run time by reducing to 2-3 years? If it takes 20 to really test it, that's fine, just trying to speed up the regression tests.

2023-06-22 21:44 UTC, PaulTalbot-INL commented
Looks like we don't get `ipopt` on the Windows computer; however, it looks like we're requesting it as part of the dependencies, so that's odd.

2023-06-23 16:25 UTC, GabrielSoto-INL commented on src/Cases.py
>                          of economic metrics for all realizations. Currently only features ``NPV''. """
this is still accurate, but it is not very clear. the keys of that dictionary are the names used in the HERON input XML script (`NPV`, `IRR`, `PI` or `LC`). I am creating an explicit list of those names and will use it in that EnumType to hopefully clarify things

2023-06-23 16:52 UTC, GabrielSoto-INL commented on src/Cases.py
>                            objective in the ``outer'' optimization.
I think the word "mapping" is confusing things. I switched it to "meta". so now there is:

- a `stats_metrics_meta` which has info on how each statistic is used. 
- a `flipped_stats_metrics_meta` which just has the optimization default flipped (max-> min and vice versa) and is only used for LC
- an `economic_metrics_meta` which has info on how each economic metric is used (e.g., how the metric is referred in TEAL vs outputted in the final CSV + a stats map)

Regarding this specific example, here I just want the names of statistics so I'm just going to pull from `stats_metrics_meta` which is the default (i.e., there was no need on my part to create a new `default_stats_metric_mapping` variable)

2023-06-23 17:39 UTC, GabrielSoto-INL commented on templates/template_driver.py
> +        opt_path_plot_vars.text = opt_path_plot_vars.text.replace('mean_NPV', new_opt_objective)
it is not, what's happening here is that the template for `opt_path` plots in the Outstreams has `mean_NPV` as the default. We replace it with `new_opt_objective` if the user has specified something other than the default

2023-06-23 17:40 UTC, GabrielSoto-INL commented on tests/integration_tests/mechanics/levelized_cost/LC_Price/heron_input__LC_Price.xml
> +      <ProjectTime>20</ProjectTime>
we can! I switched it to 20 yrs to check something and should have probably reverted back. will re-run and re-gold

2023-06-23 18:46 UTC, PaulTalbot-INL commented on src/Cases.py
>                          of economic metrics for all realizations. Currently only features ``NPV''. """
So the end of the description where it says `Currently only features "NPV"`, is that accurate?

2023-06-23 18:47 UTC, PaulTalbot-INL commented on src/Cases.py
>                            objective in the ``outer'' optimization.
Sounds good. I mostly meant, can we clarify the user-facing description in some way. Although I can't really think of a good way to improve it.

2023-06-23 21:57 UTC, PaulTalbot-INL approved these changes

2023-06-23 21:59 UTC, PaulTalbot-INL commented
This looks like it makes progress towards  #300 without completing it, so I did not mark it for closure. Let me know if I'm wrong about that!

Otherwise LGTM, tests pass, merging. If you want to announce this feature (and its limitations) on the discussion board, that would be great!

2023-06-23 22:00 UTC, merged