[WIP] Limit ramp freq
idaholab/HERON pull request #305
Opened 2023-06-21 19:56 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #304 

##### What are the significant changes in functionality due to this change request?
Limits how soon a re-ramping event can occur after the previous ramp.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-06-28 18:33 UTC, GabrielSoto-INL requested changes
Minor things to change, otherwise looks good. I ran the twin dispatch script and it looks like it's doing what it's supposed to be doing. Took me a second to understand the sign notation when capacities are negative, but makes sense now

2023-06-28 18:33 UTC, GabrielSoto-INL commented on src/dispatch/pyomo_dispatch.py
> +    limit_delta = comp.ramp_limit * cap # NOTE: if cap is negative, then this is negative.
It might be worth noting that the `cap` here might be a capacity factor, unsure if that would matter to the user?

2023-06-28 18:33 UTC, GabrielSoto-INL commented on src/dispatch/pyomo_dispatch.py
> +      @ In, bins, tuple, optional, (lower, steady, upper) binaries if limiting ramp frequency
I think the tuples here are out of order, according to the function call in `_create_ramp_limit( )`. should it be `(down, up, steady)` in this docstring?

2023-06-28 18:33 UTC, GabrielSoto-INL commented on src/dispatch/twin_pyomo_limited_ramp.py
> +  """ TODO """
missing docstrings here

2023-06-29 20:05 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +    limit_delta = comp.ramp_limit * cap # NOTE: if cap is negative, then this is negative.
would it ever be just the capacity factor, or would it always be `copperplate * factor`? I agree this formulation assumes that the ramp limit is a function of the _available_ capacity, not the _built_ capacity, which might be a faulty assumption. I will add a comment to that effect.

2023-07-03 12:23 UTC, GabrielSoto-INL approved these changes
Changes LGTM

2023-07-03 12:23 UTC, GabrielSoto-INL commented on src/dispatch/pyomo_dispatch.py
> +    limit_delta = comp.ramp_limit * cap # NOTE: if cap is negative, then this is negative.
sorry I misspoke, you are correct - I meant that it's either `built_capacity * factor` or `built_capacity`, never just the capacity factor unless the capacity is somehow set to `1`. comment looks good!

2023-07-12 20:55 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1628379/) on 9e7eaba : invalidated by @PaulTalbot-INL

TEAL plugin library change should fix error.

2023-07-13 16:54 UTC, GabrielSoto-INL commented
Merging now that tests are passing

2023-07-13 16:55 UTC, merged

2024-04-11 21:59 UTC, j-bryan commented on src/dispatch/pyomo_dispatch.py
> +        return delta >= - limit * down + eps * up
Sorry to dredge up some old work done, but I was hoping somebody could clarify why the eps=1.0 term is used here? I can see how that would remove ambiguity from the case of delta=0 when determining the the binary auxiliary variables, but why 1.0? Unless I'm misunderstanding what's happening here, we would be limiting the ramp up/down to be on the interval [eps, limit] (with appropriate signs for up/down).

2024-04-12 14:56 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +        return delta >= - limit * down + eps * up
I had similar thoughts, that led to the `#TODO needed?`. I don't recall if I tried omitting it, and then added it back when things didn't work properly, or if I never tested it. I based the implementation on some work @GabrielSoto-INL did previously, and may have just trusted those notes implicitly. Perhaps Gabe has more insight.

2024-04-15 17:32 UTC, GabrielSoto-INL commented on src/dispatch/pyomo_dispatch.py
> +        return delta >= - limit * down + eps * up
Sorry, I didn't catch that in the review. The paper Paul is referencing is this one (hadn't been published at the time): https://doi.org/10.1016/j.energy.2023.128107. The relevant parts are equations (4) and (5) in Section 3.3. In those equations, we used $\delta = 0.01$ (in the code referred to as `eps`) to ensure that the binaries $y_d$ and $y_u$ for ramping down and ramping up, respectively, are zero when power remains constant. I'll raise an issue in the repository to try to fix that. We chose a small number that made sense for our study, but I think the `eps` should be a smaller number to apply more generally, maybe scaling with capacity (which is known in the inner level)?

2024-04-15 17:46 UTC, j-bryan commented on src/dispatch/pyomo_dispatch.py
> +        return delta >= - limit * down + eps * up
Thanks for linking that paper. It does make sense that in many cases, eps=1 may be sufficiently small, but I agree that using a number smaller than 1, and one that might scale with capacity, makes sense in more general application.

2024-04-15 18:13 UTC, GabrielSoto-INL commented on src/dispatch/pyomo_dispatch.py
> +        return delta >= - limit * down + eps * up
Issue raised here: #357. Thanks for catching that @j-bryan !