The component's total activity
idaholab/HERON pull request #309
Opened 2023-08-08 06:30 UTC by BotrosHanna-INL

--------
Pull Request Description
--------
##### What issue does this change request address?

https://github.com/idaholab/HERON/issues/289

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-08-08 13:56 UTC, dylanjm requested changes
Some small changes for you to consider. Let me know your thoughts.

2023-08-08 13:56 UTC, dylanjm commented on src/DispatchManager.py
> +        cluster_year_list_of_dicts = [] # collect all component activity data for for one cluster for one year here
Could all this added logic be refactored into a separate function? The `_do_dispatch()` function is getting pretty large.

2023-08-08 13:56 UTC, dylanjm commented on src/DispatchManager.py
> +          Dict = {}
Can you use a more descriptive variable name here?

2023-08-08 13:56 UTC, dylanjm commented on src/DispatchManager.py
> +                  variable_name = "TotalActivity__"+ "__".join((str(k)).rsplit("_", 1))+ "__"+ res_name
Add whitespace between `+` here

2023-08-08 13:56 UTC, dylanjm commented on src/DispatchManager.py
> +    for y in list_of_years:
Maybe instead of `y` do ` year`

2023-08-08 13:56 UTC, dylanjm commented on src/DispatchManager.py
> +            tot_activity_per_year[v] = tot_activity_per_year[v] + d[v] * d['Days per year per cluster']
I'm curious how much we should hard-code logic relying on clusters when they may go away or are treated differently in the future.

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +fin_pre = ["sharpe", "sortino", "es", "VaR", "glr"]
Make any global variables all-caps and be more descriptive like `FINANCIAL_NAMES` or something.

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +    default_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
I would just break this out into a traditional nested for loop. It's kind of hard to read as a comprehension.

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +      sweep_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
Same comment as above.

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +      for tracker in component.get_tracking_vars():
If you want, you can use `itertools.product` to flatten some of these nested for loops.

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +    default_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
Same comment as above

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +      sweep_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
Same comment as above

2023-08-08 13:56 UTC, dylanjm commented on templates/template_driver.py
> +        #   metric_entry = x.split("_", 1)[1]
commented code

2023-08-09 15:16 UTC, BotrosHanna-INL commented on src/DispatchManager.py
> +        cluster_year_list_of_dicts = [] # collect all component activity data for for one cluster for one year here
It is 3 functions now instead of one.

2023-08-09 15:17 UTC, BotrosHanna-INL commented on src/DispatchManager.py
> +          Dict = {}
Done

2023-08-09 15:17 UTC, BotrosHanna-INL commented on src/DispatchManager.py
> +                  variable_name = "TotalActivity__"+ "__".join((str(k)).rsplit("_", 1))+ "__"+ res_name
Done

2023-08-09 15:17 UTC, BotrosHanna-INL commented on src/DispatchManager.py
> +    for y in list_of_years:
I changed it

2023-08-09 15:18 UTC, BotrosHanna-INL commented on src/DispatchManager.py
> +            tot_activity_per_year[v] = tot_activity_per_year[v] + d[v] * d['Days per year per cluster']
The function I modified was already dependent on clusters so I think for the current time we will rely on them.

2023-08-09 15:20 UTC, BotrosHanna-INL commented
Thank you so much, Dylan for taking the time to review this PR. I modified the dispatch_manager and working now on the template_driver changes.

2023-08-09 16:00 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +fin_pre = ["sharpe", "sortino", "es", "VaR", "glr"]
Done

2023-08-09 16:01 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +    default_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
make sense

2023-08-09 16:01 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +      sweep_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
I replaced it with a traditional nested "for" loop.

2023-08-09 16:04 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +      for tracker in component.get_tracking_vars():
I did not use the itertools.product before. They seem to be very useful but I will stick now with I am familiar with.

2023-08-09 16:06 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +    default_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
I replaced it with a traditional nested "for" loop.

2023-08-09 16:06 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +      sweep_stats_tot_act = [self.namingTemplates['tot_activity'].format(stats=sp, component=component.name, tracker=tracker, resource=resource) for component in components for tracker in component.g
I replaced it with a traditional nested "for" loop.

2023-08-09 16:06 UTC, BotrosHanna-INL commented on templates/template_driver.py
> +        #   metric_entry = x.split("_", 1)[1]
removed it

2023-08-28 23:15 UTC, BotrosHanna-INL commented
@dylanjm 
I have modified the optimization settings test. It takes less than 300 seconds now.

2023-08-29 13:55 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1729335/) on 1801220 : invalidated by @dylanjm

Not sure what happend. Failure in Example Plugins.

2023-08-29 15:58 UTC, joshua-cogliati-inl commented
> Job [CentOS 8](https://civet.inl.gov/job/1729335/) on [1801220](https://github.com/idaholab/HERON/commit/180122019800c8406dbacb0a1adced4ed8a0e2e1) : invalidated by @dylanjm
> 
> Not sure what happend. Failure in Example Plugins.

```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/civet/miniconda3/envs/raven_libraries/lib/python3.10/site-packages/pandas/_libs/window/aggregations.cpython-310-x86_64-linux-gnu.so
```
This looks like a conflict between the library that pandas expects and the library that is on the computer.
Of hand I am not sure why this is happening in the HERON test on Centos 8, but not on the RAVEN test, which is using the same pandas library.
py310h7cbd5c2_1, py310h7cbd5c2_1
https://civet.inl.gov/job/1729335/ versus https://civet.inl.gov/job/1731389/

2023-08-30 14:16 UTC, moosebuild commented
Job [CentOS 8](https://civet.inl.gov/job/1732813/) on eabbaaa : invalidated by @joshua-cogliati-inl

used LD_LIBRARY_PATH magic

2023-08-30 17:43 UTC, dylanjm approved these changes
Changes are good to merge.

2023-08-30 17:43 UTC, merged