Fixing KeyError when Optimization Type is not specified and New Tests
idaholab/HERON pull request #315
Opened 2023-08-17 22:02 UTC by GabrielSoto-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
#314 

##### What are the significant changes in functionality due to this change request?

1) Fixed KeyError when overriding outer Optimizer:
   - In `template_driver.py`, within `_modify_outer_optimizers()`, if the optimization type (min, max) is not specified by user then HERON will now correctly index the `economic_metrics_meta` dictionary with a previously missing key -> the statistical metric. 

2) Default stats metric:
   - In `Cases.py`, there is now a default statistical metric -> 'expectedValue'. 
   - In `Cases.py`, within `_read_optimization_settings()`, if a stats metric was not found, HERON ensures that default metric is `expectedValue`. 

3) A previously unreachable bug was found and fixed: 
    - when creating the `flipped_stats_metrics_meta` dict, there was a reference error that altered the regular `stats_metrics_meta` dict
    - using a deepcopy fixes the problem

4) New XML input script test directory:
    - `tests/integration_tests/XML_check`
    - New tests check that when running a HERON script, that the `outer.xml` has the correct settings
        -  tests if `<type>` is not specified in `optimization_settings`, that HERON selects the correct type depending on both the opt metric (NPV, LC, etc.) and the stats metric (expected value, value at risk, etc.).  

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2023-08-17 23:05 UTC, GabrielSoto-INL commented
"oh, well they run perfectly fine locally..."
I forgot that the Model <executable> node for RAVEN in the `outer.xml` will have the path for `raven_framework` and when I golded it, it had my local path. Unsure how to make this work when running on Civet or Github Actions...

2023-08-18 14:00 UTC, PaulTalbot-INL commented
> "oh, well they run perfectly fine locally..." I forgot that the Model node for RAVEN in the `outer.xml` will have the path for `raven_framework` and when I golded it, it had my local path. Unsure how to make this work when running on Civet or Github Actions...

Hm, that is tricky. I don't think we have a way to tell the XML differ to exclude particular node paths, but maybe that's the start of an answer?

2023-08-18 15:09 UTC, dylanjm commented on templates/template_driver.py
> +        type_node.text = case.economic_metrics_meta[opt_metric]['stats_map'][stats_metric]['optimization_default']
Nothing to change here, but I feel that if we are indexing this far into an object, we should just make it a class instead of a dict. Maybe one day we can justify a refactor.

2023-08-18 15:12 UTC, dylanjm requested changes

2023-08-18 15:12 UTC, dylanjm commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +      <executable>C:\Users\sotogj\projects\raven\raven_framework</executable>
Is this going to cause errors when run on the testing machine?

2023-08-18 15:15 UTC, dylanjm commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +      <executable>C:\Users\sotogj\projects\raven\raven_framework</executable>
Sorry, didn't see the conversation above earlier, looks like you already caught this.

2023-08-21 13:36 UTC, GabrielSoto-INL commented on templates/template_driver.py
> +        type_node.text = case.economic_metrics_meta[opt_metric]['stats_map'][stats_metric]['optimization_default']
that's a really good idea, maybe I can fix it in a future PR

2023-09-11 19:44 UTC, GabrielSoto-INL commented
RAVEN (via rook) can now ignore certain XML nodes from the XML differ test. With this new feature, we can now test outer XMLs in HERON and ignore the RAVEN executable path

2023-09-11 19:45 UTC, GabrielSoto-INL commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +      <executable>C:\Users\sotogj\projects\raven\raven_framework</executable>
this particular node is now ignored in the XML diff tests

2023-09-12 15:11 UTC, dylanjm approved these changes
No suggested changes

2023-09-12 15:11 UTC, merged