BayesianOpt fix
idaholab/HERON pull request #344
Opened 2024-03-15 22:56 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #312 Closes #308 

##### What are the significant changes in functionality due to this change request?
Re-implements Anthoney's original PR with only the changes necessary for BayesianOpt.

More work needs to be done to (1) set BayesianOpt as the default optimizer, (2) convert the workshop cases.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2024-03-15 22:57 UTC, PaulTalbot-INL commented on src/Cases.py
> +    debug = cls._specs_debug()
this may read as weird; I split out some of the long input specs into their own class methods.

2024-03-18 22:02 UTC, dylanjm requested changes
One small change. I'm honestly suprised we don't have to regold all test files since they will default to BO now and I would expect at least some differences in results.

2024-03-18 22:02 UTC, dylanjm commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +      <executable>C:\Users\TALBPW\projects\raven\raven_framework</executable>
I don't think we want to commit this path to the golded tests right?

2024-03-19 14:58 UTC, PaulTalbot-INL commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +      <executable>C:\Users\TALBPW\projects\raven\raven_framework</executable>
man, I thought I fixed that. Thanks for catching!

2024-03-19 14:59 UTC, PaulTalbot-INL commented
> One small change. I'm honestly suprised we don't have to regold all test files since they will default to BO now and I would expect at least some differences in results.

They aren't defaulting to BO yet, just this one test. That would be another step, that I haven't had time to do. This at least makes it available.

2024-03-19 15:54 UTC, dylanjm requested changes
Pesky typo

2024-03-19 15:54 UTC, dylanjm commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +<Simulatio verbosity="all">
Oh dang, I think the `n` got accidentally deleted which is causing the diff for this test.

2024-03-19 20:36 UTC, PaulTalbot-INL commented on tests/integration_tests/XML_check/gold/optimization_type_mean_LC_o/outer.xml
> +<Simulatio verbosity="all">
hilarious. I would expect a much larger error, but I guess it's a small thing.

2024-03-19 21:33 UTC, dylanjm approved these changes
Changes are good to merge and tests have been added to ensure this new feature works as it should.

2024-03-19 21:33 UTC, merged