Creates HERON/data directory to store common HERON data.
idaholab/HERON pull request #351
Opened 2024-04-01 22:05 UTC by joshua-cogliati-inl

--------
Pull Request Description
--------
##### What issue does this change request address?

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2024-04-02 18:39 UTC, GabrielSoto-INL requested changes
Changes LGTM and add a lot better organization of auxiliary HERON data. As had been previously discussed, added a suggestion for updating the input specs to instruct the user about using the %HERON_DATA% environment variable

2024-04-02 18:39 UTC, GabrielSoto-INL commented on src/Placeholders.py
In this file, it might be worth updating the InputData descriptions within the `get_input_specs( )` methods of the `ARMA(Placeholder)` and `Function(Placeholder)` classes to talk about using `%HERON_Data%` instead of/in addition to `%HERON%`. In the modified files, these are lines `169` and `264` respectively (could not find a way to link to them directly in this comment).

2024-04-08 21:35 UTC, joshua-cogliati-inl commented on src/Placeholders.py
Okay, I added descriptions of HERON_DATA to those get_input_specs.

2024-04-09 14:31 UTC, PaulTalbot-INL approved these changes

2024-04-09 14:34 UTC, merged