Fixing aux parameter in ramping constraint
idaholab/HERON pull request #358
Opened 2024-04-17 15:54 UTC by GabrielSoto-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
#357 

##### What are the significant changes in functionality due to this change request?
Auxiliary parameter for binary variables (used only when ramp frequencies are selected by user) is now a smaller value scaling with limit. This prevents the lower bound for ramping to be unintentionally constrained. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2024-04-17 16:03 UTC, dylanjm requested changes
Minor request for more clarification in comment

2024-04-17 16:03 UTC, dylanjm commented on src/dispatch/PyomoRuleLibrary.py
> +    eps = 1e-6*limit # aux parameter to force binaries to behave
Can expound on your comment a bit more. Things like why would it not behave and why choose such a small number.

2024-04-18 20:14 UTC, GabrielSoto-INL commented on src/dispatch/PyomoRuleLibrary.py
> +    eps = 1e-6*limit # aux parameter to force binaries to behave
I added more explanation to the comments here. Additionally, added a xlsx file to the relevant regression test with some sanity checking for the signs, here is a screenshot: 
![image](https://github.com/idaholab/HERON/assets/109242402/f6f78fbe-6d25-4747-9a8c-36bb00bb3c26)

2024-04-18 20:54 UTC, dylanjm approved these changes
Changes are good to merge.

2024-04-24 19:12 UTC, merged