[WIP] Refactoring template driver to dynamically create RAVEN workflows
idaholab/HERON pull request #391
Opened 2024-11-18 16:26 UTC by j-bryan

--------
Pull Request Description
--------
##### What issue does this change request address?
#390 

##### What are the significant changes in functionality due to this change 
This pull request restructures the templating system used to generate RAVEN workflows.
- The RAVEN template and the template driver are separated into different classes.
- A FeatureDriver class is introduced to define changes to a RAVEN template XML to add a single feature. For example, adding a Grid sampler to the RAVEN XML is done with one FeatureDriver instance, while adding the model used by the workflow is done with a different FeatureDriver.
- FeatureDriver instances can be composed and grouped in FeatureCollection objects.
- The template driver uses feature drivers to edit a template object.
- Edits to the template XML are intended to be strictly additive. One aspect of the previous TemplateDriver implementation that I felt made the current state of the template XML unclear at times was not knowing which nodes were present at any given point in the code due to numerous additions, deletions, and edits made throughout the TemplateDriver. Moving to a strictly additive scheme while starting from a much smaller template XML reframes the template driver's function as adding the desired features to the XML, rather than deleting all other unneeded entities from the XML, as was common practice.
- Addition of a "flat" RAVEN workflow template for specific cases which can be run as flat workflows.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2024-11-18 16:40 UTC, PaulTalbot-INL commented
Wow, this is quite an effort! Do you have any diagramming or writeup for the logic flow? I think it's starting to make sense glancing over it, but some developer documentation would help get us up to speed on this new structure. Thanks for your work on this!

2025-01-21 22:28 UTC, dylanjm requested changes
Some minor changes and discussion points. I read heavily my assigned sections and then did a quick look over the rest of the files. I will review once more when all changes are submitted. 

I was thinking, it might be nice to add some linting checks to our automated testing. Nothing that stops the tests from running, but just checking to make sure we are consistent. Almost like a coverage summary but for linting. @joshua-cogliati-inl  @caleb-sitton-inl  what are your thoughts on this?

2025-01-21 22:28 UTC, dylanjm commented on doc/developers/templates.md
> +However, a balance must be struct between configuring existing templates and creating new templates.
`struck` instead of `struct`?

2025-01-21 22:28 UTC, dylanjm commented on src/Cases.py
> +    module = importlib.import_module(f'templates.template_driver', package="HERON")
no need for f-string anymore.

2025-01-21 22:28 UTC, dylanjm commented on src/DispatchManager.py
> +    # for now, just `summariz`e what we found -> take it from the first source
perhaps a typo?

2025-01-21 22:28 UTC, dylanjm commented on src/Economics.py
> +      if (param := getattr(self, param_name)).type == "RandomVariable":
oh a fancy walrus operator. Nothing to change, just cool to see.

2025-01-21 22:28 UTC, dylanjm commented on src/Placeholders.py
> +    return self.type == typ
Good refactoring here.

2025-01-21 22:28 UTC, dylanjm commented on src/_utils.py
> -     return lru_cache(maxsize=None)(user_function)
I can't remember why we had this check in there before. I think it had something to do with python versions not having `cache` yet.

2025-01-21 22:28 UTC, dylanjm commented on src/Placeholders.py
> +    return hutils.get_csv_structure(self._target_file, case.get_year_name(), case.get_time_name())
Do we need to modify the ARMA placeholder class method `get_synthhist_structure()`? Should we do a similar caching in Placeholders instead of inside utils?

2025-01-21 22:28 UTC, dylanjm commented on templates/debug_template.py
> +    #   1. MonteCarlo sampler: Used for samplingfrom .ime series ROM and distributions for swept/optimized
`sampling from time series` typo

2025-01-21 22:28 UTC, dylanjm commented on templates/debug_template.py
> +    #   2. CustomSampler sampler: Used for getting a static historyfrom . CSV file.
`static history from a `

2025-01-21 22:28 UTC, dylanjm commented on templates/debug_template.py
> +    has_csv_source = any(s.is_type("CSV") for s in sources)
For the time being, should we assert that both are not TRUE? Only one can be TRUE (until we fully implement?)

2025-01-21 22:28 UTC, dylanjm commented on templates/debug_template.py
> +      if any(s.is_type("ARMA") for s in sources):
`if has_arma_source` would use the previously computed value and would be more readable imo. Tiny change up to you.

2025-01-22 15:38 UTC, j-bryan commented on src/DispatchManager.py
> +    # for now, just `summariz`e what we found -> take it from the first source
An overzealous find and replace with `sed` I think

2025-01-22 15:42 UTC, j-bryan commented on src/_utils.py
> -     return lru_cache(maxsize=None)(user_function)
The `functools` documentation says `cache` was added in 3.9. Makes sense to have needed that recently, but it's safe to remove now that we require at least 3.10.

2025-01-22 16:03 UTC, j-bryan commented on templates/debug_template.py
> +    has_csv_source = any(s.is_type("CSV") for s in sources)
I think this would be good. Since that's the case for all templates, not just the debug template, I'll add something to throw an error in that case in the `TemplateDriver` class. I'll also add a test to check that that fails.

2025-01-22 16:56 UTC, j-bryan commented on templates/debug_template.py
> +      if any(s.is_type("ARMA") for s in sources):
Nice catch on this one. I see no reason to not use the previously computed value. I'll make that edit.

2025-01-22 17:16 UTC, j-bryan commented on src/Placeholders.py
> +    return hutils.get_csv_structure(self._target_file, case.get_year_name(), case.get_time_name())
Good question, I hadn't looked too closely at that `get_synthhist_structure` function. Looking over the documentation for `functools.cache` again, I don't think there would be a difference in caching behavior between how I implemented it in the CSV placeholder class and how it's done in the `get_synthhist_structure` function, despite the distinction that my comment makes. That said, I think having a `get_structure` method attached to the placeholder classes provides a nicer interface and better encapsulation than having to make a call to the function in `_utils`. For example, in `DispatchManager.DispatchRunner._get_structure` (line 711), `structure = hutils.get_synthhist_structure(source._target_file)` could be reduced to `structure = source.get_structure()`. Whether this is worth additional refactoring right now is another question though. What are your thoughts?

2025-01-22 19:35 UTC, dylanjm commented on src/Placeholders.py
> +    return hutils.get_csv_structure(self._target_file, case.get_year_name(), case.get_time_name())
That would be a good refactor, but I think it can probably wait until this PR is merged to address it.

2025-01-22 23:01 UTC, joshua-cogliati-inl reviewed
Some comments on templates/snippets

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/base.py
> +    Alternate constructor which instantiates a new RavenSnippet objectfrom .n existing XML node
Should "objectfrom .n existing" be "object from an existing"?

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/base.py
> +  RavenSnippet class objects describe one contiguous snippet of RAVEN XML, inheritingfrom .he xml.etree.ElementTree.Element
Should "inheritingfrom .he" be "inheriting from the"?

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/distributions.py
> +  Make a new distribution classfrom .he RAVEN input spec for that class
change "classfrom .he" to "class from the"?

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/files.py
> +    self.set("type", str(value))
If the type of value is str, why is `str(value)` needed? (Ditto for "path")

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/models.py
> +      loc = "Samplers|MonteCarlo@name:mc_arma_dispatch"  # where this is pointing 9/10 times
Should the doc string mention that this is the default for loc?

2025-01-22 23:01 UTC, joshua-cogliati-inl commented on templates/snippets/steps.py
> +    # Create an Assembler nodefrom .he entity
Change "nodefrom .he" to "node from the"?

2025-01-23 18:51 UTC, j-bryan commented on templates/snippets/models.py
> +      loc = "Samplers|MonteCarlo@name:mc_arma_dispatch"  # where this is pointing 9/10 times
Probably a good idea. I'll add that.

2025-01-23 18:55 UTC, j-bryan commented on templates/snippets/files.py
> +    self.set("type", str(value))
It's unnecessary as long as the input type is respected. I'll remove in the interest of cleaner code.

2025-01-23 19:42 UTC, joshua-cogliati-inl commented
> I was thinking, it might be nice to add some linting checks to our automated testing. Nothing that stops the tests from running, but just checking to make sure we are consistent. Almost like a coverage summary but for linting. @joshua-cogliati-inl @caleb-sitton-inl what are your thoughts on this?

We use pylint on RAVEN, so this seems reasonable. (pylint is available in conda and pypi)

2025-01-23 20:09 UTC, j-bryan commented
I was aware of pylint but hadn't made much use of it before. I was looking through some issues it brought up in my code for this PR and fixed some of the issues it brought up. I agree it would be good to add in a way similar to how it's used by RAVEN.

2025-01-23 20:50 UTC, GabrielSoto-INL submitted a review, later dismissed
Couple of linting errors, some comments and questions. Fantastic work so far, big fan of the changes

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/template_driver.py
> +      raise self.raiseAnError(ValueError, "Mixing ARMA and CSV sources is not yet supported! "
the `raise` here should be removed, the line should just be `self.raiseAnError( ... `

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/template_driver.py
> +    return not any([comp.get_capacity(None, raw=True).is_parametric() for comp in components])
from my Pylinter (https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/use-a-generator.html), you can remove the square brackets here and just have `any(comp.get_capacity(...`

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +from .snippets.distributions import Distribution, Uniform
should `Uniform` here be `NewDistribution`? I dont see a `Uniform` class in the snippets

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +  def loadTemplate(self) -> None:
for these three "public API functions" the input parameter list is different from the parent `Template` class that `RavenTemplate` inherits, should look at that one and consolidate/update

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    template_path = this_file_dir / self.template_path
where is `self.template_path` being set? should it be in the __init__?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    xml_file = dest_dir / self.write_name
for `self.write_name`, same comment as for `self.template_path`

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +  def _get_statistical_results_vars(self, case: HeronCase, components: list[Component]) -> list[str]:
worth mentioning in a comment that this is used in the bilevel template and the "deterministic" version is used in the flat template?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +  def _pickled_rom_from_source(self, source: Source) -> PickledROM:
could this be used in the `_load_pickled_rom` above? or vice-versa. from a cursory view, looks like there might be some duplicate logic

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    parsed_child = parse_to_snippets(child)
just double checking, we wouldn't need a stop criteria for the recursion because we are looping through a finite iterable in the `node` right?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +      opt_stat, = get_statistics([statistic], case.stats_metrics_meta)
remove the comma after `opt_stat`

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +from .snippets.distributions import Distribution, Uniform
I see `Uniform` is used in `_create_new_sampled_capacity` below, but it does exist in `snippets.distributions`

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    vars, consts = self._create_sampler_variables(case, components)
should rename `vars` since it's already a built-in function in Python, happens in other places

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +      """
less indentation

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    for sampled_var, vals in vars.items():
just loop over `vars` since `vals` isn't used

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/raven_template.py
> +    self._initialize_runinfo(case)
this call has one argument, but the method below requires two. I see it is overloaded in other template classes and when running `super()` two arguments are provided as required in the `RavenTemplate` class. wonder if there's a cleaner way of handling this. perhaps the `RavenTemplate` class should be an abstract class? so that the `_initialize_runinfo` method is only run starting from inherited classes?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/flat_templates.py
> +    grid_sampler.denoises = case.get_num_samples()
if this is a flat run, wouldn't the number of samples be 1? should there be a check?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/xml_utils.py
> +  node_pattern = re.compile(r"(?P<tag>[^/\[]+)(\[@(?P<attrib>[^=]+)=(?P<quote>['\"])(?P<value>[^'\"]+)(?P=quote)\])?")
wow, words in a regex string!!!

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/xml_utils.py
> +    """
less indent

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/xml_utils.py
> +  elif isinstance(val, dict):
no `elif`s after a return statement

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/write_inner.py
> +    """
less indent

2025-01-23 20:50 UTC, GabrielSoto-INL commented on templates/write_inner.py
> +def alias_to_xpath(alias: str) -> str:
ok, took me a second to understand the modifications to `modifyInput` below. This seems like a useful method, and seems to be written to be very general though it is used for only a specific purpose in `modifyInput`. could `alias_to_xpath` be moved to a more general `utils` script?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on tests/unit_tests/test_listproperty.py
> +    self._list = []
docstrings for the methods

2025-01-23 20:50 UTC, GabrielSoto-INL commented on tests/integration_tests/mechanics/csv_and_arma_fail/tests
Great addition!

2025-01-23 20:50 UTC, GabrielSoto-INL commented on tests/integration_tests/mechanics/debug_mode/gold/dispatch_print.csv
columns ordered differently on purpose?

2025-01-23 20:50 UTC, GabrielSoto-INL commented on tests/integration_tests/mechanics/pyomo_options/gold/Sweep_Runs_o/sweep.csv
I see, it's a static history so no need for statistics on the results.

2025-01-23 20:50 UTC, GabrielSoto-INL commented on tests/integration_tests/mechanics/test_cashplot/gold/Runs_o/dispatch.nc
any idea why these files have changed?

2025-01-23 21:00 UTC, j-bryan commented on templates/template_driver.py
> +    return not any([comp.get_capacity(None, raw=True).is_parametric() for comp in components])
Oh yeah, using the generator expression directly instead of collecting that generator in a list first would work the same and is a little cleaner. I'll change that.

2025-01-23 21:03 UTC, j-bryan commented on templates/raven_template.py
> +from .snippets.distributions import Distribution, Uniform
This is because I'm doing something sneaky to create the distribution classes. Since there are so many that RAVEN can accept, I'm actually parsing the RAVEN input specs for the distribution classes and dynamically creating RavenSnippet classes for them. You can look at `templates/snippets/distributions.py` to see how I'm doing that. The downside is I don't think any linter will be able to find those classes I create.

2025-01-23 21:09 UTC, joshua-cogliati-inl reviewed
I have reviewed HERON/tests/unit_tests/snippets and HERON/templates/xml.

2025-01-23 21:09 UTC, joshua-cogliati-inl commented on tests/unit_tests/snippets/test_optimizers.py
> +
Do we have a policy (or precedent) that allows skipping doc strings in tests? Otherwise, they probably need to be added.

2025-01-23 21:11 UTC, j-bryan commented on templates/raven_template.py
> +    template_path = this_file_dir / self.template_path
`self.template_path` is set by the subclasses, but I agree that this could've been done better. I'll see if I can revise that while changing these public API methods to better match the RAVEN super class definitions.

2025-01-23 21:13 UTC, j-bryan commented on templates/raven_template.py
> +  def loadTemplate(self) -> None:
I can do that. I'm not a huge fan of the RAVEN class's function signatures for these methods but it is what it is, I guess

2025-01-23 22:40 UTC, j-bryan commented on templates/raven_template.py
> +  def _pickled_rom_from_source(self, source: Source) -> PickledROM:
Turns out `_pickled_rom_from_source` isn't even called anywhere, in favor of `_load_pickled_rom`. Nice catch, I'll remove the unused method.

2025-01-23 22:42 UTC, j-bryan commented on templates/raven_template.py
> +    parsed_child = parse_to_snippets(child)
Correct. It's depth-first recursion, so the function will recurse on child nodes until a leaf node in the XML tree is reached (`node` has no `child`), so that has the base case to stop recursion built in.

2025-01-23 22:43 UTC, j-bryan commented on templates/raven_template.py
> +      opt_stat, = get_statistics([statistic], case.stats_metrics_meta)
Fixed in previous commit

2025-01-23 22:44 UTC, j-bryan commented on templates/raven_template.py
> +    vars, consts = self._create_sampler_variables(case, components)
Fixed in previous commit https://github.com/idaholab/HERON/pull/391/commits/3ad53df26cd58e3820adb35901c524c7fcbd7cb0

2025-01-23 22:45 UTC, j-bryan commented on templates/raven_template.py
> +      """
Fixed in previous commit https://github.com/idaholab/HERON/pull/391/commits/3ad53df26cd58e3820adb35901c524c7fcbd7cb0

2025-01-23 22:46 UTC, j-bryan commented on templates/raven_template.py
> +    for sampled_var, vals in vars.items():
Fixed in previous commit https://github.com/idaholab/HERON/pull/391/commits/3ad53df26cd58e3820adb35901c524c7fcbd7cb0

2025-01-23 22:57 UTC, j-bryan commented on templates/raven_template.py
> +    self._initialize_runinfo(case)
I agree there should be a cleaner way to handle this. The call stack gets a bit messy here. I'll see what I can come up with.

2025-01-24 01:29 UTC, j-bryan commented on templates/flat_templates.py
> +    grid_sampler.denoises = case.get_num_samples()
I think we could actually get rid of this line all together. In `TemplateDriver.create_workflow`, we've checked that the static history CSV has only 1 time series sample, and the "denoises" parameter is already set to 1 in the `flat_multi_config.xml` template file. There should be nothing to set here.

2025-01-24 01:37 UTC, j-bryan commented on templates/write_inner.py
> +def alias_to_xpath(alias: str) -> str:
With the way this `write_inner.py` file gets copied around, I don't think relative imports from somewhere else in HERON would work as intended. The `alias_to_xpath` function could be useful elsewhere though. Any ideas of a good way to handle that?

I'll add a comment in `modifyInput` to help clarify what's happening with the `alias_to_xpath` function.

2025-01-24 01:39 UTC, j-bryan commented on templates/write_inner.py
> +def alias_to_xpath(alias: str) -> str:
In general, do you know why this custom syntax is used for aliases? I don't see a reason that the XPath couldn't be used instead, and that would make these helper functions like `alias_to_xpath` redundant. Changing to using XPath would be a breaking change though, so maybe not worth making that change right now.

2025-01-27 17:02 UTC, j-bryan commented on tests/integration_tests/mechanics/debug_mode/gold/dispatch_print.csv
The column reordering isn't intentional, just how things happened to shake out with how the refactored code orders things. The diff GitHub calculates here is a little misleading though. The real difference is in the way the `prefix` column is expressed. Since there is no inner/outer workflow for this case (prefixes values expressed as {i_outer}_{i_inner} or something like that), the prefix values are just ints for the flat workflow.

2025-01-27 17:20 UTC, j-bryan commented on tests/integration_tests/mechanics/test_cashplot/gold/Runs_o/dispatch.nc
There was a typo in `template_driver.py` which failed to add some values to the `dispatch.nc` database. The line in question is here: https://github.com/idaholab/HERON/blob/bb70736bbe3f1ac6b91786f86c0d7715b558025f/templates/template_driver.py#L447

The variable group `GRO_outer_debug_dispath` should have been `GRO_outer_debug_dispatch`. The `dispatch.nc` file here has changed to reflect the addition of these values.

2025-01-28 16:42 UTC, dylanjm requested changes
Just two minor changes.

2025-01-28 16:42 UTC, dylanjm commented on templates/decorators.py
> +    self.property_instance = property_instance
I hate to do this, but this class is missing docstrings.

2025-01-28 16:42 UTC, dylanjm commented on templates/decorators.py
> +    self.fget = fget
Same with this class

2025-01-28 18:25 UTC, j-bryan commented on templates/decorators.py
> +    self.property_instance = property_instance
Dang, I knew there would be at least 1

2025-01-28 22:06 UTC, dylanjm approved these changes
I'm thinking these changes look pretty good. Nothing stands out to me to halt this PR any further. Tests have been added for new functionality and features remain compatible with previous versions of HERON, so no need for a user group email (since this is more of a developer improvement anyway.)

2025-01-29 02:14 UTC, merged