[WIP] Add optional case_info nodes for HERON
idaholab/HERON pull request #41
Opened 2020-10-08 00:34 UTC by dylanjm

Refs #38

2020-10-08 20:22 UTC, dylanjm commented
@PaulTalbot-INL I'm able to run a few modified test-cases containing `<label>` nodes. But I'm not sure where we want it to end up. I thought it may end up in `disp_results.csv` but it doesn't.

2020-10-09 00:20 UTC, PaulTalbot-INL reviewed
A couple comments below.

I think the ultimate goal is to have these available in a Function method via `case.get_labels()` so we'll want to add a test that checks they can be obtained there.

2020-10-09 00:20 UTC, PaulTalbot-INL commented on src/Cases.py
> +        descr=r"""provides static label information to the model; unused in computation."""
Can we specify here how these are accessed in the Functions? This is all the user manual they're going to get on this subject.

2020-10-09 00:20 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # ooooooooo # I don't think this gets run!
does it get run?

2020-10-09 00:20 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +          input_node.text += ', GRO_case_labels'
I don't think we need these in the outer/inner now, right? If they're on "case" they should be accessible already in the `meta` in the Functions, I believe.

2020-10-12 16:13 UTC, dylanjm commented on src/Cases.py
> +    # ooooooooo # I don't think this gets run!
Nope, but was showing as an error in my IDE hah, shall I remove this?

2020-10-12 16:14 UTC, dylanjm commented on templates/template_driver.py
> +          input_node.text += ', GRO_case_labels'
Do we want the case_info in the sweep output file? This was my initial way of getting it to show up there. Would there be a more straight-forward way?

2020-10-12 16:46 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # ooooooooo # I don't think this gets run!
it's fine, I was curious for my own sake. I'd leave the comment as you have it, though, so the next guy to come along can be aware.

2020-10-12 16:47 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +          input_node.text += ', GRO_case_labels'
Hm, interesting. Yeah, I see what you mean, good point. If this gets it in the output csv for the user automagically, that's good.

2020-10-12 17:25 UTC, dylanjm commented on templates/template_driver.py
> +          input_node.text += ', GRO_case_labels'
It's also showing up in the `disp_debug.csv` which I can take out if it wouldn't be necessary there.

2020-10-12 18:00 UTC, dylanjm commented on src/Cases.py
> +    # ooooooooo # I don't think this gets run!
I was curious about this. It actually looks like `template_driver.py` duplicates all these functions. I noticed then when I first tried to add the aliases for the labels in these functions and they didn't show up. It also looks like they are nearly identical to the `template_driver.py` functions. Perhaps it's dead code we can remove?

2020-10-12 18:21 UTC, PaulTalbot-INL commented on src/Cases.py
> +    # ooooooooo # I don't think this gets run!
I think at one point Case was meant to also be the template writer, then I scrapped that for scope and bloat reasons. I suspect you're right.

2020-10-12 19:43 UTC, PaulTalbot-INL commented
civet seems to be locked up right now; hopefully that's resolved soon.

2020-10-12 19:56 UTC, dylanjm commented
@PaulTalbot-INL I added an integration test which is just an extended `production_flex` test. Let me know if that's sufficient.

2020-10-12 20:03 UTC, PaulTalbot-INL commented
Yeah, it looks fine. It can become a great test in the future for testing what gets sent into the Functions, so standalone test is fine. I think we're just waiting on some documentation and the automatic tests, or did I miss the docs being added?

2020-10-12 20:05 UTC, dylanjm commented
@PaulTalbot-INL I updated the documentation, but I just put all the points together on referencing `meta['HERON']['Case']`. I'm updating that now. Other than that, after the tests pass it should be good to go.

2020-10-13 14:00 UTC, PaulTalbot-INL requested changes

2020-10-13 14:00 UTC, PaulTalbot-INL commented on tests/integration_tests/labels/transfers.py
> +  return data, meta
Do you retrieve the labels anywhere as part of this test? I think that would show it's doing what it's supposed to.

You can cut out most of the comments in this file too, if you want.

2020-10-13 16:37 UTC, dylanjm commented on tests/integration_tests/labels/transfers.py
> +  return data, meta
That should be updated now.

2020-10-13 16:40 UTC, PaulTalbot-INL commented on tests/integration_tests/labels/transfers.py
> +  return data, meta
Hm, interesting. In general I don't think we'd want to pass those back, but I think we'll happily ignore it even if we do. This mechanically works fine.

2020-10-13 16:40 UTC, PaulTalbot-INL approved these changes

2020-10-13 16:40 UTC, merged