Milestone changes
idaholab/HERON pull request #59
Opened 2021-01-04 16:54 UTC by dylanjm

--------
Pull Request Description
--------
##### What issue does this change request address?

All the changes required for the milestone due in December

##### What are the significant changes in functionality due to this change request?

Will add in a bit. 

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-01-21 20:09 UTC, dylanjm commented
@PaulTalbot-INL This PR is ready for a first round of comments. I haven't added the command line flags addition to this PR.

2021-01-21 20:39 UTC, PaulTalbot-INL commented
We should retest after idaholab/raven#1409 is merged. I'll start reviewing.

2021-01-21 21:12 UTC, PaulTalbot-INL requested changes
This was a huge merge request, props for handling it well.

There's a few comments to address, largely stylistic (always a fun part of integrating into a new team).

There's one big item, and that's dealing with sampled variables that aren't component properties, such as storage buy/sell prices and bid adders, that we don't have a way to handle in the HERON input right now. We can either find a way to add them, or pull that feature from this PR and address it one following this.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/ArmaBypass.py
> +
NB: hopefully we can come up with an easier way to do this in the future; for now, I do agree we should leave it in as progress towards a proper debug setting.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/ArmaBypass.py
> +
I wonder if we could generalize this external model to accept arguments like number of clusters/years/time steps, names of signals, signal values, so that it can mimic whatever ARMA as a bypass. Something to consider for the future.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/Cases.py
> +    )
is this autoformatting or are you doing it manually?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/Cases.py
> +  @staticmethod
Do we gain anything from this aside from readability?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/Cases.py
> -    # no changes needed here!
Can we leave this in? Almost surely we'll want to use this section in the near future, and this will help whomever does that maintain the organization.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +#rutils.add_path(os.path.abspath(cashflow_path))
looks like this line can go

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +    """ TODO """
docstrings need adding here

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +    magics = ['NPP_bid_adjust', 'HTSE_built_capacity', 'IES_delta_cap'] # XXX DO NOT MERGE FIXME TODO
this needs to be a real system, not an ad-hoc approach, before we merge this; possibly as a distinct PR we can merge into this one, or merge before this one.

Essentially, we need to allow `<constant>` and `<variable>` nodes from OUTER to be included in the magic passthroughs to INNER without the user having to update the list. Maybe HERON can write this list as arguments to the DispatchManager in a node, or something? Open to design ideas.

Furthermore, I don't think there's a way to systematically add parametric variables that aren't part of unit descriptions (such as these magic terms) to the HERON input, so that might need to come with the PR.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +        # Chop up raven_vars for sources to corresponding segment/cluster, year, and time
I feel this lost some meaning by removing the indent arrow. What did we gain?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +        # Find the info for this cluster -> FIXME this should be restructured so searching isn't necessary!
again with indent notation changing, what benefit do we get from taking out the notational structures?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +        # TODO: Better way to get pivotParameterID?
this comment was resolved (thank you for that, btw)

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +              ## of the project life
did this not fit on the 120 character line limit? I believe that limitation is in the RAVEN standards we inherit in HERON, intended to reduce vertical expansion reasonably

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +                }
I find this structure, with single indent for line continuation, quite difficult to parse when scanning through code quickly. Is there a reason to use this over the recommend tabbing (which I believe is double indent or in line with the start of the overflow syntax on the previous line)?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +                ## of once per division?
this takes up a lot of vertical space; is the gain worth it?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +                  # FIXME multiplicity? -> should not apply to Recurring.Yearly
this comment has been resolved and can be removed

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> -    # end Year loop
unless these loop endings are incorrect, let's leave them in; it can save some tricky errors when trying to add something outside of the innermost loop, which is probably why they were added in the first place

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +          #raven.Cluster =
this comment looks like it can be removed

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +          print(f'DEBUGG saving year {y} cluster {c} var {var_name}')
debugg can be commented or removed

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +          pass
this ... doesn't look like it does anything. Do we use the override time option any time?

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +    # # TODO am I overwriting this slicer in a bad way?
it looks like this whole chunk can go, as the slicing has been improved below it.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/Placeholders.py
> +    print(f'DEBUGG target: "{self._target_file}"')
this print can be dropped

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/SerializationManager.py
> +        print(external_funcs)
this can go

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +        self._debug_pyomo_print(m)
how much work would it be to add a verbosity setting to the dispatchers to enable levels of printing? I think that would be quite useful. Maybe we make that an issue to tackle once this is merged.

2021-01-21 21:12 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +      #   minimum = comp.get_minimum(meta)[0][cap_res]
these three lines can go

2021-01-21 21:12 UTC, PaulTalbot-INL commented on templates/template_driver.py
> +    print(f'DEBUGG {comp_name} max {max_cap}, min {min_cap}, delta {delta}, initial {initial}.')
this can go

2021-01-21 22:03 UTC, dylanjm commented on src/dispatch/pyomo_dispatch.py
> +        self._debug_pyomo_print(m)
Yeah, I think that would be a quick and feasible addition to the code. Also, should we create issues for the HERON wishlist you had put together in the past few weeks?

2021-01-21 22:09 UTC, PaulTalbot-INL commented on src/dispatch/pyomo_dispatch.py
> +        self._debug_pyomo_print(m)
Definitely. Let's workshop the list and break it into reasonable issues.

2021-01-25 17:06 UTC, moosebuild commented
All [jobs](https://civet.inl.gov/event/62562/) on f4d480a : invalidated by @PaulTalbot-INL

update to RAVEN with required HERON changes

2021-01-25 17:36 UTC, dylanjm commented on src/DispatchManager.py
> +    """ TODO """
Do you remember what this method was added for? Not sure how to document this method.

2021-01-25 17:42 UTC, dylanjm commented on src/DispatchManager.py
> -    # end Year loop
I have no qualms putting them back, but I would think that if nested loops are starting to become tricky that's a sign to refactor. I'll put them back and refactor for another PR.

2021-01-25 17:58 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/666502/) on f4d480a : invalidated by @milljm

somehow, this machine (mobuild56) is still determined to capture serial-meowbuild jobs...

2021-01-25 18:03 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> +    """ TODO """
Maybe ... I think maybe it was used to allow time to exist without getting it from an ARMA, perhaps. Either that, or it's related to clustering. If you need more, I can go looking for where I called it, and that might shake loose the description. Sorry.

2021-01-25 18:06 UTC, PaulTalbot-INL commented on src/DispatchManager.py
> -    # end Year loop
That's a good point. I'd down for a refactor of this section if you have an idea how we could make it cleaner.

2021-01-25 18:11 UTC, dylanjm commented on src/DispatchManager.py
> +                }
Both methods are encouraged by PEP8. The nice thing about this format is that you can modify entries of the dict and git will show only those changes. I will modify it back. 

PEP8 for reference: 
 https://www.python.org/dev/peps/pep-0008/#indentation

2021-01-26 17:38 UTC, PaulTalbot-INL commented on src/DispatchManager.py
>            pass_vars[v] = getattr(raven, v)
Is `vaprs_needed` really correct?

2021-01-26 17:40 UTC, dylanjm commented on src/DispatchManager.py
>            pass_vars[v] = getattr(raven, v)
That must've been a mistake apologies. haha

2021-01-26 19:21 UTC, dylanjm commented
@PaulTalbot-INL All tests passing if you want to give it a once over.

2021-01-26 22:10 UTC, PaulTalbot-INL approved these changes

2021-01-26 22:40 UTC, merged