Modular ValuedParams
idaholab/HERON pull request #83
Opened 2021-05-04 22:11 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #25

##### What are the significant changes in functionality due to this change request?
Modularizes the ValuedParams for easier extension.

Also allows the ValuedParams factory to flag which types of VPs are acceptable for specific actions. Currently this splits between "transfer" and everything else.

Clarifies documentation for allowable VPs.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-05-04 22:20 UTC, PaulTalbot-INL commented
@dhill2522 This may affect some of the work on the dispatcher(s) you're working on; I hope not, but let me know and I can help straighten it out.

2021-05-04 22:59 UTC, dylanjm requested changes
Looks good to me. A few questions on some of the design of the VPs. Also, I believe this will close #65

2021-05-04 22:59 UTC, dylanjm commented on src/Economics.py
> +import ValuedParams
Isn't this file deleted? I think there is some confusion on my end between `ValuedParams/` (folder) vs. `ValuedParams` (file) vs. `ValueParam` (class/file).

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Function.py
> +    return [self._method_name]
Might be a matter of personal taste, but I feel like there should be an explanation of why the return value is casted into an list.

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Function.py
> +    return [self._method_name]
Help me understand... the return value of this function will always return a `List[str]` with a singular element in it correct? It seems fishy to me to require it to be a list.

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Function.py
> +      @ Out, value, dict, dictionary of resulting evaluation as {vars: vals}
mismatch in variable names `value` vs. `data` for the first return value.

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Linear.py
> +    return []
This follows on from the previous `read()` discussion. Is `read()` meant to be a function of pure side-effects (changing state)? Do we need to return anything from `read()`?

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Linear.py
> +      @ Out, value, dict, dictionary of resulting evaluation as {vars: vals}
mismatch in variable  names `value` vs. `balance`.

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/Linear.py
> +      @ Out, meta, dict, dictionary of meta (possibly changed during evaluation)
mismatch in variable names `meta` vs. `inputs`

2021-05-04 22:59 UTC, dylanjm commented on src/ValuedParams/SyntheticHistory.py
> +    self._source_kind = 'ARMA'
Can we depend on `SyntheticHistory`s always coming from an ARMA?

2021-05-05 14:09 UTC, PaulTalbot-INL commented on src/ValuedParams/Function.py
> +    return [self._method_name]
The return of the "read" function provides a list of references that will later be used to connect the Placeholder objects to the ValuedParam instances. Previously, this list has contained multiple entries for some VPs; I don't think that still true. However, I think it's likely that more pieces of information could be needed by some VPs in the future, so the list preserves that flexibility. I can try and clarify that in the base class VP docstrings.

2021-05-05 14:10 UTC, PaulTalbot-INL commented on src/ValuedParams/SyntheticHistory.py
> +    self._source_kind = 'ARMA'
Currently, yes; someday soon, probably no.

2021-05-05 14:14 UTC, dylanjm commented on src/ValuedParams/Function.py
> +    return [self._method_name]
Okay, that makes sense. Yeah, any clarification in the base class would be great.

2021-05-05 14:36 UTC, PaulTalbot-INL commented on src/Economics.py
> +import ValuedParams
In this revision, this is referring to the module, from which the CashFlows need access to the ValuedParams.factory. If it would notably clearer, I could use
```python
from ValuedParams import factory as vp_factory
```
and propagate that change forward.

2021-05-05 14:37 UTC, PaulTalbot-INL commented on src/ValuedParams/Function.py
> +      @ Out, value, dict, dictionary of resulting evaluation as {vars: vals}
fixed

2021-05-05 14:37 UTC, PaulTalbot-INL commented on src/ValuedParams/Linear.py
> +    return []
responded above

2021-05-05 14:39 UTC, PaulTalbot-INL commented on src/ValuedParams/Linear.py
> +      @ Out, value, dict, dictionary of resulting evaluation as {vars: vals}
fixed

2021-05-05 14:41 UTC, PaulTalbot-INL commented
Comments have been addressed.

There are a lot of integration tests covering (I'm fairly sure) every kind of ValuedParam at least once; each valued entry in HERON inputs is a ValuedParam, so they get used all over the place.

We could probably use more thorough testing of each kind of VP for each "kind" of input (economics, capacity, transfer function), but I think that would be a good PR for another time, personally.

2021-05-05 14:56 UTC, dylanjm approved these changes

2021-05-05 15:08 UTC, merged