new Activity ValuedParam
idaholab/HERON pull request #85
Opened 2021-05-05 18:47 UTC by PaulTalbot-INL

--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #84 

##### What are the significant changes in functionality due to this change request?
Adds the `<activity>` node, which does a simple lookup of dispatch activity for the associated component.

For example, if a `<Produces>` component consumes `steam` to make `electricity`, a `CashFlow` might include the driver:
```xml
<driver>
  <activity>steam</activity>
  <multiplier>-1</multiplier>
</driver>
```
to suggest a cashflow of -1 * amount of steam consumed (negative * negative makes positive).

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual and xsd schema. If the input syntax change deprecates existing input files, a conversion script needs to be added (see Conversion Scripts).
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/HERON/wiki/Code-Standards) for details.
- [ ] 4. Automated Tests should pass.
- [ ] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large tes.
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added, the the analytic documentation must be updated/added.
- [ ] 9. If any test used as a basis for documentation examples have been changed, the associated documentation must be reviewed and assured the text matches the example.

2021-05-05 18:48 UTC, PaulTalbot-INL commented
Before this is merged, there's one thing I need to fix, and that's error checking on the resource named.

2021-05-05 18:48 UTC, PaulTalbot-INL commented on src/ValuedParams/Activity.py
> +    # FIXME how to confirm this component actually produces/consumes/stores this resource??
I'm looking for ideas here; we don't have a reference to the Component, but we need to check  that the named resource is actually produced or consumed by Component. Ideas?

2021-05-05 19:24 UTC, dylanjm commented on src/ValuedParams/Activity.py
> +    # FIXME how to confirm this component actually produces/consumes/stores this resource??
Are you married to idea of doing the conditional check in this method on read-in? Could we "finalize" a component with conditional check? Or can we interrogate the `spec` variable? Or does `spec` only contain the current xml node information?

2021-05-05 19:27 UTC, dylanjm commented on src/ValuedParams/Activity.py
> +    # FIXME how to confirm this component actually produces/consumes/stores this resource??
Also to make sure I understand the current dilema, we need to check for user-error cases like this:

```
 <Component name="electr_market">
      <demands resource="steam" dispatch="dependent">
        <capacity>
          <fixed_value>-2</fixed_value>
        </capacity>
      </demands>
      <economics>
        <lifetime>30</lifetime>
        <CashFlow name="e_sales" type="repeating" taxable='True' inflation='none' mult_target='False'>
          <driver>
            <activity>electricity</activity>
            <multiplier>-1</multiplier>
          </driver>
          <reference_price>
      </economics>
    </Component>
```

Where `resource='steam'` conflicts with `<activity>electricity</activity>`

2021-05-05 19:40 UTC, dylanjm requested changes
Looks good. Just need to solve the error handling issue.

2021-05-05 19:41 UTC, PaulTalbot-INL commented on src/ValuedParams/Activity.py
> +    # FIXME how to confirm this component actually produces/consumes/stores this resource??
That's true, we could do a "finalize" checking later, as long as it's still in the HERON "compile time" and before RAVEN starts running and producing awful errors. That's a good idea.

Your example is good, yes, that would be an input that I'd expect to see an intelligent error for.

2021-05-06 18:36 UTC, dylanjm approved these changes
All the logic, documentation, and naming checks out. Looks good.

2021-05-06 18:37 UTC, merged